// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/vocabulary/common.proto

package vocabulary

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResultStatus int32

const (
	ResultStatus_Success     ResultStatus = 0
	ResultStatus_MaxLimit    ResultStatus = 1
	ResultStatus_Repeated    ResultStatus = 2
	ResultStatus_NotExisted  ResultStatus = 3
	ResultStatus_DBException ResultStatus = 4
	ResultStatus_Empty       ResultStatus = 5
)

var ResultStatus_name = map[int32]string{
	0: "Success",
	1: "MaxLimit",
	2: "Repeated",
	3: "NotExisted",
	4: "DBException",
	5: "Empty",
}

var ResultStatus_value = map[string]int32{
	"Success":     0,
	"MaxLimit":    1,
	"Repeated":    2,
	"NotExisted":  3,
	"DBException": 4,
	"Empty":       5,
}

func (x ResultStatus) String() string {
	return proto.EnumName(ResultStatus_name, int32(x))
}

func (ResultStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_138760f71682afbb, []int{0}
}

type DirectionType int32

const (
	DirectionType_Double DirectionType = 0
	DirectionType_FromTo DirectionType = 1
	DirectionType_ToFrom DirectionType = 2
)

var DirectionType_name = map[int32]string{
	0: "Double",
	1: "FromTo",
	2: "ToFrom",
}

var DirectionType_value = map[string]int32{
	"Double": 0,
	"FromTo": 1,
	"ToFrom": 2,
}

func (x DirectionType) String() string {
	return proto.EnumName(DirectionType_name, int32(x))
}

func (DirectionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_138760f71682afbb, []int{1}
}

type DateInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Begin                string   `protobuf:"bytes,3,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  string   `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DateInfo) Reset()         { *m = DateInfo{} }
func (m *DateInfo) String() string { return proto.CompactTextString(m) }
func (*DateInfo) ProtoMessage()    {}
func (*DateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_138760f71682afbb, []int{0}
}

func (m *DateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DateInfo.Unmarshal(m, b)
}
func (m *DateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DateInfo.Marshal(b, m, deterministic)
}
func (m *DateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DateInfo.Merge(m, src)
}
func (m *DateInfo) XXX_Size() int {
	return xxx_messageInfo_DateInfo.Size(m)
}
func (m *DateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DateInfo proto.InternalMessageInfo

func (m *DateInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *DateInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DateInfo) GetBegin() string {
	if m != nil {
		return m.Begin
	}
	return ""
}

func (m *DateInfo) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

type PlaceInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location             string   `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceInfo) Reset()         { *m = PlaceInfo{} }
func (m *PlaceInfo) String() string { return proto.CompactTextString(m) }
func (*PlaceInfo) ProtoMessage()    {}
func (*PlaceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_138760f71682afbb, []int{1}
}

func (m *PlaceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceInfo.Unmarshal(m, b)
}
func (m *PlaceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceInfo.Marshal(b, m, deterministic)
}
func (m *PlaceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceInfo.Merge(m, src)
}
func (m *PlaceInfo) XXX_Size() int {
	return xxx_messageInfo_PlaceInfo.Size(m)
}
func (m *PlaceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceInfo proto.InternalMessageInfo

func (m *PlaceInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PlaceInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlaceInfo) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type RequestInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Id                   uint64   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestInfo) Reset()         { *m = RequestInfo{} }
func (m *RequestInfo) String() string { return proto.CompactTextString(m) }
func (*RequestInfo) ProtoMessage()    {}
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_138760f71682afbb, []int{2}
}

func (m *RequestInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestInfo.Unmarshal(m, b)
}
func (m *RequestInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestInfo.Marshal(b, m, deterministic)
}
func (m *RequestInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestInfo.Merge(m, src)
}
func (m *RequestInfo) XXX_Size() int {
	return xxx_messageInfo_RequestInfo.Size(m)
}
func (m *RequestInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestInfo proto.InternalMessageInfo

func (m *RequestInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RequestInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RequestInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type RequestList struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	List                 []string `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	Status               uint32   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestList) Reset()         { *m = RequestList{} }
func (m *RequestList) String() string { return proto.CompactTextString(m) }
func (*RequestList) ProtoMessage()    {}
func (*RequestList) Descriptor() ([]byte, []int) {
	return fileDescriptor_138760f71682afbb, []int{3}
}

func (m *RequestList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestList.Unmarshal(m, b)
}
func (m *RequestList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestList.Marshal(b, m, deterministic)
}
func (m *RequestList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestList.Merge(m, src)
}
func (m *RequestList) XXX_Size() int {
	return xxx_messageInfo_RequestList.Size(m)
}
func (m *RequestList) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestList.DiscardUnknown(m)
}

var xxx_messageInfo_RequestList proto.InternalMessageInfo

func (m *RequestList) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestList) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *RequestList) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *RequestList) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type RequestPage struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Status               uint32   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Number               int32    `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Page                 int32    `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestPage) Reset()         { *m = RequestPage{} }
func (m *RequestPage) String() string { return proto.CompactTextString(m) }
func (*RequestPage) ProtoMessage()    {}
func (*RequestPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_138760f71682afbb, []int{4}
}

func (m *RequestPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestPage.Unmarshal(m, b)
}
func (m *RequestPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestPage.Marshal(b, m, deterministic)
}
func (m *RequestPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPage.Merge(m, src)
}
func (m *RequestPage) XXX_Size() int {
	return xxx_messageInfo_RequestPage.Size(m)
}
func (m *RequestPage) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPage.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPage proto.InternalMessageInfo

func (m *RequestPage) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *RequestPage) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RequestPage) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *RequestPage) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type RequestFilter struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Number               int32    `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Key                  string   `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestFilter) Reset()         { *m = RequestFilter{} }
func (m *RequestFilter) String() string { return proto.CompactTextString(m) }
func (*RequestFilter) ProtoMessage()    {}
func (*RequestFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_138760f71682afbb, []int{5}
}

func (m *RequestFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestFilter.Unmarshal(m, b)
}
func (m *RequestFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestFilter.Marshal(b, m, deterministic)
}
func (m *RequestFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestFilter.Merge(m, src)
}
func (m *RequestFilter) XXX_Size() int {
	return xxx_messageInfo_RequestFilter.Size(m)
}
func (m *RequestFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestFilter.DiscardUnknown(m)
}

var xxx_messageInfo_RequestFilter proto.InternalMessageInfo

func (m *RequestFilter) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *RequestFilter) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *RequestFilter) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *RequestFilter) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RequestFilter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ReqUpdateFilter struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Values               []string `protobuf:"bytes,6,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUpdateFilter) Reset()         { *m = ReqUpdateFilter{} }
func (m *ReqUpdateFilter) String() string { return proto.CompactTextString(m) }
func (*ReqUpdateFilter) ProtoMessage()    {}
func (*ReqUpdateFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_138760f71682afbb, []int{6}
}

func (m *ReqUpdateFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUpdateFilter.Unmarshal(m, b)
}
func (m *ReqUpdateFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUpdateFilter.Marshal(b, m, deterministic)
}
func (m *ReqUpdateFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUpdateFilter.Merge(m, src)
}
func (m *ReqUpdateFilter) XXX_Size() int {
	return xxx_messageInfo_ReqUpdateFilter.Size(m)
}
func (m *ReqUpdateFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUpdateFilter.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUpdateFilter proto.InternalMessageInfo

func (m *ReqUpdateFilter) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqUpdateFilter) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqUpdateFilter) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqUpdateFilter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ReqUpdateFilter) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqUpdateFilter) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type ReplyInfo struct {
	Uid                  string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Key                  string       `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Id                   uint64       `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Updated              uint64       `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyInfo) Reset()         { *m = ReplyInfo{} }
func (m *ReplyInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyInfo) ProtoMessage()    {}
func (*ReplyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_138760f71682afbb, []int{7}
}

func (m *ReplyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyInfo.Unmarshal(m, b)
}
func (m *ReplyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyInfo.Marshal(b, m, deterministic)
}
func (m *ReplyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyInfo.Merge(m, src)
}
func (m *ReplyInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyInfo.Size(m)
}
func (m *ReplyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyInfo proto.InternalMessageInfo

func (m *ReplyInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReplyInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReplyInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyInfo) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type ReplyStatus struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyStatus) Reset()         { *m = ReplyStatus{} }
func (m *ReplyStatus) String() string { return proto.CompactTextString(m) }
func (*ReplyStatus) ProtoMessage()    {}
func (*ReplyStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_138760f71682afbb, []int{8}
}

func (m *ReplyStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStatus.Unmarshal(m, b)
}
func (m *ReplyStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStatus.Marshal(b, m, deterministic)
}
func (m *ReplyStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStatus.Merge(m, src)
}
func (m *ReplyStatus) XXX_Size() int {
	return xxx_messageInfo_ReplyStatus.Size(m)
}
func (m *ReplyStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStatus proto.InternalMessageInfo

func (m *ReplyStatus) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ReplyStatus) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type AttributeInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 uint32   `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Key                  string   `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Begin                string   `protobuf:"bytes,6,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  string   `protobuf:"bytes,7,opt,name=end,proto3" json:"end,omitempty"`
	Remark               string   `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Time                 int64    `protobuf:"varint,9,opt,name=time,proto3" json:"time,omitempty"`
	Updated              int64    `protobuf:"varint,10,opt,name=updated,proto3" json:"updated,omitempty"`
	Created              int64    `protobuf:"varint,11,opt,name=created,proto3" json:"created,omitempty"`
	Creator              string   `protobuf:"bytes,12,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,13,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttributeInfo) Reset()         { *m = AttributeInfo{} }
func (m *AttributeInfo) String() string { return proto.CompactTextString(m) }
func (*AttributeInfo) ProtoMessage()    {}
func (*AttributeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_138760f71682afbb, []int{9}
}

func (m *AttributeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeInfo.Unmarshal(m, b)
}
func (m *AttributeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeInfo.Marshal(b, m, deterministic)
}
func (m *AttributeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeInfo.Merge(m, src)
}
func (m *AttributeInfo) XXX_Size() int {
	return xxx_messageInfo_AttributeInfo.Size(m)
}
func (m *AttributeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeInfo proto.InternalMessageInfo

func (m *AttributeInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AttributeInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AttributeInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *AttributeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AttributeInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AttributeInfo) GetBegin() string {
	if m != nil {
		return m.Begin
	}
	return ""
}

func (m *AttributeInfo) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *AttributeInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *AttributeInfo) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *AttributeInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *AttributeInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *AttributeInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *AttributeInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func init() {
	proto.RegisterEnum("omo.msp.vocabulary.ResultStatus", ResultStatus_name, ResultStatus_value)
	proto.RegisterEnum("omo.msp.vocabulary.DirectionType", DirectionType_name, DirectionType_value)
	proto.RegisterType((*DateInfo)(nil), "omo.msp.vocabulary.DateInfo")
	proto.RegisterType((*PlaceInfo)(nil), "omo.msp.vocabulary.PlaceInfo")
	proto.RegisterType((*RequestInfo)(nil), "omo.msp.vocabulary.RequestInfo")
	proto.RegisterType((*RequestList)(nil), "omo.msp.vocabulary.RequestList")
	proto.RegisterType((*RequestPage)(nil), "omo.msp.vocabulary.RequestPage")
	proto.RegisterType((*RequestFilter)(nil), "omo.msp.vocabulary.RequestFilter")
	proto.RegisterType((*ReqUpdateFilter)(nil), "omo.msp.vocabulary.ReqUpdateFilter")
	proto.RegisterType((*ReplyInfo)(nil), "omo.msp.vocabulary.ReplyInfo")
	proto.RegisterType((*ReplyStatus)(nil), "omo.msp.vocabulary.ReplyStatus")
	proto.RegisterType((*AttributeInfo)(nil), "omo.msp.vocabulary.AttributeInfo")
}

func init() {
	proto.RegisterFile("proto/vocabulary/common.proto", fileDescriptor_138760f71682afbb)
}

var fileDescriptor_138760f71682afbb = []byte{
	// 655 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6b, 0xdb, 0x4c,
	0x10, 0x8e, 0xf5, 0xe1, 0xd8, 0xe3, 0x38, 0x11, 0x4b, 0x08, 0xe2, 0x85, 0x97, 0x06, 0x9d, 0x42,
	0x0e, 0x0e, 0x34, 0x87, 0x9e, 0x1b, 0x9c, 0x40, 0x21, 0x29, 0x61, 0x93, 0x42, 0x29, 0xf4, 0xb0,
	0x96, 0xa6, 0x66, 0x89, 0xa4, 0x55, 0x56, 0xab, 0x34, 0xa6, 0xff, 0xa2, 0xd0, 0x1f, 0xd1, 0x7f,
	0x59, 0x76, 0xb4, 0x56, 0xec, 0x24, 0x3e, 0xb4, 0xb7, 0xe7, 0x99, 0xdd, 0x99, 0x67, 0x76, 0x3e,
	0x16, 0xfe, 0xaf, 0xb4, 0x32, 0xea, 0xe4, 0x41, 0xa5, 0x62, 0xd6, 0xe4, 0x42, 0x2f, 0x4e, 0x52,
	0x55, 0x14, 0xaa, 0x9c, 0x90, 0x9d, 0x31, 0x55, 0xa8, 0x49, 0x51, 0x57, 0x93, 0xa7, 0x0b, 0xc9,
	0x67, 0x18, 0x4c, 0x85, 0xc1, 0x0f, 0xe5, 0x37, 0xc5, 0x22, 0xf0, 0x1b, 0x99, 0xc5, 0xbd, 0xc3,
	0xde, 0xd1, 0x90, 0x5b, 0xc8, 0x18, 0x04, 0xa5, 0x28, 0x30, 0xf6, 0xc8, 0x44, 0x98, 0xed, 0x43,
	0x38, 0xc3, 0xb9, 0x2c, 0x63, 0x9f, 0x8c, 0x2d, 0xb1, 0xbe, 0x58, 0x66, 0x71, 0xd0, 0xfa, 0x62,
	0x99, 0x25, 0x57, 0x30, 0xbc, 0xce, 0x45, 0xfa, 0x37, 0xa1, 0xff, 0x83, 0x41, 0xae, 0x52, 0x61,
	0xa4, 0x5a, 0x46, 0xef, 0x78, 0xf2, 0x15, 0x46, 0x1c, 0xef, 0x1b, 0xac, 0xcd, 0x86, 0x80, 0x11,
	0xf8, 0x77, 0xb8, 0x70, 0xf1, 0x2c, 0x64, 0xbb, 0xe0, 0xc9, 0x8c, 0x02, 0x05, 0xdc, 0x93, 0x99,
	0x0d, 0xaf, 0x2a, 0xd4, 0xc2, 0x28, 0xed, 0x12, 0xed, 0x78, 0x32, 0xef, 0xc2, 0x5f, 0xca, 0xda,
	0xbc, 0x12, 0x7e, 0xd5, 0xd9, 0x5b, 0x77, 0xb6, 0x6f, 0xc9, 0x65, 0x6d, 0x62, 0xff, 0xd0, 0xb7,
	0x6f, 0xb1, 0x98, 0x1d, 0x40, 0xbf, 0x36, 0xc2, 0x34, 0x35, 0x49, 0x8d, 0xb9, 0x63, 0x89, 0xec,
	0x84, 0xae, 0xc5, 0x1c, 0xed, 0xb5, 0x4a, 0x68, 0x2c, 0x8d, 0xd3, 0x72, 0x6c, 0xc5, 0xdd, 0x5b,
	0x75, 0xb7, 0xf6, 0xb2, 0x29, 0x66, 0xa8, 0xe9, 0x5d, 0x21, 0x77, 0xcc, 0xa6, 0x50, 0x89, 0x39,
	0x92, 0x58, 0xc8, 0x09, 0x27, 0x3f, 0x60, 0xec, 0xa4, 0x2e, 0x64, 0x6e, 0x50, 0x6f, 0x14, 0x5b,
	0x3a, 0x7b, 0x4f, 0xce, 0x1b, 0x85, 0x5c, 0x99, 0x83, 0xa7, 0x32, 0xef, 0x43, 0xf8, 0x20, 0xf2,
	0x06, 0xe3, 0xb0, 0x1d, 0x08, 0x22, 0xc9, 0xaf, 0x1e, 0xec, 0x71, 0xbc, 0xff, 0x54, 0x65, 0xc2,
	0xa0, 0xd3, 0xdf, 0x87, 0x50, 0x7d, 0x2f, 0x51, 0x3b, 0xf9, 0x96, 0x2c, 0x6b, 0xed, 0xbd, 0x68,
	0xa5, 0xff, 0x8a, 0x46, 0xb0, 0xa2, 0xb1, 0xd6, 0x93, 0xf0, 0x59, 0x4f, 0x0e, 0xa0, 0x4f, 0x97,
	0xea, 0xb8, 0x4f, 0x5d, 0x71, 0x2c, 0xf9, 0xd9, 0x83, 0x21, 0xc7, 0x2a, 0x5f, 0xfc, 0xf3, 0x18,
	0xbd, 0x5b, 0xeb, 0xec, 0xe8, 0xed, 0x9b, 0xc9, 0xcb, 0xbd, 0x9a, 0x90, 0xc4, 0x0d, 0x5d, 0xeb,
	0x7a, 0x17, 0xc3, 0x76, 0x43, 0xe5, 0xc8, 0x28, 0xdb, 0x80, 0x2f, 0x69, 0x72, 0x6a, 0x87, 0xa2,
	0x73, 0xb0, 0xfd, 0x48, 0x55, 0x86, 0x94, 0xd6, 0x98, 0x13, 0xb6, 0x79, 0x15, 0xf5, 0x7c, 0x99,
	0x57, 0x51, 0xcf, 0x93, 0xdf, 0x1e, 0x8c, 0xdf, 0x1b, 0xa3, 0xe5, 0xac, 0xd9, 0xb8, 0xc0, 0x6d,
	0xee, 0x5e, 0x97, 0x3b, 0x83, 0xc0, 0x2c, 0x2a, 0xa4, 0xd7, 0x8c, 0x39, 0xe1, 0x6e, 0x13, 0x83,
	0x95, 0x4d, 0x74, 0x55, 0x08, 0xd7, 0x3a, 0xd0, 0xae, 0x7d, 0xff, 0x95, 0xb5, 0xdf, 0xee, 0xd6,
	0xde, 0xd6, 0x5d, 0x63, 0x21, 0xf4, 0x5d, 0x3c, 0x68, 0x67, 0xac, 0x65, 0xa4, 0x2c, 0x0b, 0x8c,
	0x87, 0x87, 0xbd, 0x23, 0x9f, 0x13, 0x5e, 0x2d, 0x08, 0x90, 0x79, 0x49, 0xed, 0x49, 0xaa, 0x91,
	0x4e, 0x46, 0xed, 0x89, 0xa3, 0xdd, 0x89, 0xd2, 0xf1, 0x0e, 0x09, 0x2c, 0xe9, 0xda, 0x34, 0x8c,
	0xd7, 0xa7, 0xe1, 0x38, 0x85, 0x1d, 0x8e, 0x75, 0x93, 0x1b, 0x57, 0xe1, 0x11, 0x6c, 0xdf, 0x34,
	0x69, 0x8a, 0x75, 0x1d, 0x6d, 0xb1, 0x1d, 0x18, 0x5c, 0x89, 0xc7, 0x4b, 0x59, 0x48, 0x13, 0xf5,
	0x2c, 0xe3, 0x58, 0x91, 0x58, 0xe4, 0xb1, 0x5d, 0x80, 0x8f, 0xca, 0x9c, 0x3f, 0xca, 0xda, 0x72,
	0x9f, 0xed, 0xc1, 0x68, 0x7a, 0x76, 0xfe, 0x98, 0x62, 0x65, 0x7f, 0xa5, 0x28, 0x60, 0x43, 0x08,
	0xcf, 0x8b, 0xca, 0x2c, 0xa2, 0xf0, 0xf8, 0x14, 0xc6, 0x53, 0xa9, 0x31, 0xb5, 0x27, 0xb7, 0xb6,
	0xb2, 0x00, 0xfd, 0xa9, 0x6a, 0x66, 0x39, 0x46, 0x5b, 0x16, 0x5f, 0x68, 0x55, 0xdc, 0xaa, 0xa8,
	0x67, 0xf1, 0xad, 0xb2, 0x2c, 0xf2, 0xce, 0xd8, 0x97, 0xe8, 0xf9, 0xaf, 0x3d, 0xeb, 0x93, 0xe5,
	0xf4, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x17, 0xdb, 0x77, 0xf0, 0xd0, 0x05, 0x00, 0x00,
}
