// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/vocabulary/concept.proto

package vocabulary

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConceptInfo struct {
	Type                 uint32         `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uid                  string         `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Cover                string         `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Remark               string         `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Table                string         `protobuf:"bytes,6,opt,name=table,proto3" json:"table,omitempty"`
	Time                 int64          `protobuf:"varint,7,opt,name=time,proto3" json:"time,omitempty"`
	Updated              int64          `protobuf:"varint,8,opt,name=updated,proto3" json:"updated,omitempty"`
	Created              int64          `protobuf:"varint,9,opt,name=created,proto3" json:"created,omitempty"`
	Creator              string         `protobuf:"bytes,10,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string         `protobuf:"bytes,11,opt,name=operator,proto3" json:"operator,omitempty"`
	Parent               string         `protobuf:"bytes,12,opt,name=parent,proto3" json:"parent,omitempty"`
	Scene                uint32         `protobuf:"varint,13,opt,name=scene,proto3" json:"scene,omitempty"`
	Attributes           []string       `protobuf:"bytes,31,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Privates             []string       `protobuf:"bytes,32,rep,name=privates,proto3" json:"privates,omitempty"`
	Children             []*ConceptInfo `protobuf:"bytes,33,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ConceptInfo) Reset()         { *m = ConceptInfo{} }
func (m *ConceptInfo) String() string { return proto.CompactTextString(m) }
func (*ConceptInfo) ProtoMessage()    {}
func (*ConceptInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f4eb41a88802c3b, []int{0}
}

func (m *ConceptInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConceptInfo.Unmarshal(m, b)
}
func (m *ConceptInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConceptInfo.Marshal(b, m, deterministic)
}
func (m *ConceptInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConceptInfo.Merge(m, src)
}
func (m *ConceptInfo) XXX_Size() int {
	return xxx_messageInfo_ConceptInfo.Size(m)
}
func (m *ConceptInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConceptInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConceptInfo proto.InternalMessageInfo

func (m *ConceptInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ConceptInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConceptInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ConceptInfo) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ConceptInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ConceptInfo) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *ConceptInfo) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ConceptInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ConceptInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ConceptInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ConceptInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ConceptInfo) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ConceptInfo) GetScene() uint32 {
	if m != nil {
		return m.Scene
	}
	return 0
}

func (m *ConceptInfo) GetAttributes() []string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *ConceptInfo) GetPrivates() []string {
	if m != nil {
		return m.Privates
	}
	return nil
}

func (m *ConceptInfo) GetChildren() []*ConceptInfo {
	if m != nil {
		return m.Children
	}
	return nil
}

type ReqConceptAdd struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cover                string   `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Remark               string   `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Table                string   `protobuf:"bytes,6,opt,name=table,proto3" json:"table,omitempty"`
	Parent               string   `protobuf:"bytes,7,opt,name=parent,proto3" json:"parent,omitempty"`
	Operator             string   `protobuf:"bytes,8,opt,name=operator,proto3" json:"operator,omitempty"`
	Scene                uint32   `protobuf:"varint,9,opt,name=scene,proto3" json:"scene,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqConceptAdd) Reset()         { *m = ReqConceptAdd{} }
func (m *ReqConceptAdd) String() string { return proto.CompactTextString(m) }
func (*ReqConceptAdd) ProtoMessage()    {}
func (*ReqConceptAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f4eb41a88802c3b, []int{1}
}

func (m *ReqConceptAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqConceptAdd.Unmarshal(m, b)
}
func (m *ReqConceptAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqConceptAdd.Marshal(b, m, deterministic)
}
func (m *ReqConceptAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqConceptAdd.Merge(m, src)
}
func (m *ReqConceptAdd) XXX_Size() int {
	return xxx_messageInfo_ReqConceptAdd.Size(m)
}
func (m *ReqConceptAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqConceptAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqConceptAdd proto.InternalMessageInfo

func (m *ReqConceptAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqConceptAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqConceptAdd) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ReqConceptAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqConceptAdd) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *ReqConceptAdd) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ReqConceptAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqConceptAdd) GetScene() uint32 {
	if m != nil {
		return m.Scene
	}
	return 0
}

type ReqConceptUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Type                 uint32   `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Cover                string   `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Remark               string   `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Scene                uint32   `protobuf:"varint,7,opt,name=scene,proto3" json:"scene,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqConceptUpdate) Reset()         { *m = ReqConceptUpdate{} }
func (m *ReqConceptUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqConceptUpdate) ProtoMessage()    {}
func (*ReqConceptUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f4eb41a88802c3b, []int{2}
}

func (m *ReqConceptUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqConceptUpdate.Unmarshal(m, b)
}
func (m *ReqConceptUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqConceptUpdate.Marshal(b, m, deterministic)
}
func (m *ReqConceptUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqConceptUpdate.Merge(m, src)
}
func (m *ReqConceptUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqConceptUpdate.Size(m)
}
func (m *ReqConceptUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqConceptUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqConceptUpdate proto.InternalMessageInfo

func (m *ReqConceptUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqConceptUpdate) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqConceptUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqConceptUpdate) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ReqConceptUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqConceptUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqConceptUpdate) GetScene() uint32 {
	if m != nil {
		return m.Scene
	}
	return 0
}

type ReplyConceptInfo struct {
	Info                 *ConceptInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyConceptInfo) Reset()         { *m = ReplyConceptInfo{} }
func (m *ReplyConceptInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyConceptInfo) ProtoMessage()    {}
func (*ReplyConceptInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f4eb41a88802c3b, []int{3}
}

func (m *ReplyConceptInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyConceptInfo.Unmarshal(m, b)
}
func (m *ReplyConceptInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyConceptInfo.Marshal(b, m, deterministic)
}
func (m *ReplyConceptInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyConceptInfo.Merge(m, src)
}
func (m *ReplyConceptInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyConceptInfo.Size(m)
}
func (m *ReplyConceptInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyConceptInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyConceptInfo proto.InternalMessageInfo

func (m *ReplyConceptInfo) GetInfo() *ConceptInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyConceptInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyConceptList struct {
	Flag                 string         `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	Status               *ReplyStatus   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*ConceptInfo `protobuf:"bytes,11,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReplyConceptList) Reset()         { *m = ReplyConceptList{} }
func (m *ReplyConceptList) String() string { return proto.CompactTextString(m) }
func (*ReplyConceptList) ProtoMessage()    {}
func (*ReplyConceptList) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f4eb41a88802c3b, []int{4}
}

func (m *ReplyConceptList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyConceptList.Unmarshal(m, b)
}
func (m *ReplyConceptList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyConceptList.Marshal(b, m, deterministic)
}
func (m *ReplyConceptList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyConceptList.Merge(m, src)
}
func (m *ReplyConceptList) XXX_Size() int {
	return xxx_messageInfo_ReplyConceptList.Size(m)
}
func (m *ReplyConceptList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyConceptList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyConceptList proto.InternalMessageInfo

func (m *ReplyConceptList) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

func (m *ReplyConceptList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyConceptList) GetList() []*ConceptInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyConceptAttrs struct {
	Concept              string       `protobuf:"bytes,1,opt,name=concept,proto3" json:"concept,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Attributes           []string     `protobuf:"bytes,11,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyConceptAttrs) Reset()         { *m = ReplyConceptAttrs{} }
func (m *ReplyConceptAttrs) String() string { return proto.CompactTextString(m) }
func (*ReplyConceptAttrs) ProtoMessage()    {}
func (*ReplyConceptAttrs) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f4eb41a88802c3b, []int{5}
}

func (m *ReplyConceptAttrs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyConceptAttrs.Unmarshal(m, b)
}
func (m *ReplyConceptAttrs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyConceptAttrs.Marshal(b, m, deterministic)
}
func (m *ReplyConceptAttrs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyConceptAttrs.Merge(m, src)
}
func (m *ReplyConceptAttrs) XXX_Size() int {
	return xxx_messageInfo_ReplyConceptAttrs.Size(m)
}
func (m *ReplyConceptAttrs) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyConceptAttrs.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyConceptAttrs proto.InternalMessageInfo

func (m *ReplyConceptAttrs) GetConcept() string {
	if m != nil {
		return m.Concept
	}
	return ""
}

func (m *ReplyConceptAttrs) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyConceptAttrs) GetAttributes() []string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func init() {
	proto.RegisterType((*ConceptInfo)(nil), "omo.msp.vocabulary.ConceptInfo")
	proto.RegisterType((*ReqConceptAdd)(nil), "omo.msp.vocabulary.ReqConceptAdd")
	proto.RegisterType((*ReqConceptUpdate)(nil), "omo.msp.vocabulary.ReqConceptUpdate")
	proto.RegisterType((*ReplyConceptInfo)(nil), "omo.msp.vocabulary.ReplyConceptInfo")
	proto.RegisterType((*ReplyConceptList)(nil), "omo.msp.vocabulary.ReplyConceptList")
	proto.RegisterType((*ReplyConceptAttrs)(nil), "omo.msp.vocabulary.ReplyConceptAttrs")
}

func init() {
	proto.RegisterFile("proto/vocabulary/concept.proto", fileDescriptor_7f4eb41a88802c3b)
}

var fileDescriptor_7f4eb41a88802c3b = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0x8e, 0xeb, 0xd4, 0x49, 0x26, 0xed, 0xaf, 0xfc, 0x2b, 0x84, 0x56, 0x91, 0xda, 0xba, 0x56,
	0x91, 0x72, 0x4a, 0xa5, 0xf6, 0xc0, 0x81, 0x53, 0x40, 0xa2, 0x42, 0x02, 0x21, 0x5c, 0x01, 0x12,
	0xe2, 0xe2, 0xd8, 0x53, 0x58, 0x61, 0x7b, 0xdd, 0xf5, 0x3a, 0x52, 0x6f, 0x9c, 0x78, 0x02, 0x1e,
	0x83, 0x03, 0x2f, 0xc1, 0xc3, 0xf0, 0x16, 0x68, 0xc7, 0x4e, 0xe2, 0x86, 0xba, 0x58, 0x55, 0x6f,
	0xfb, 0xcd, 0xcc, 0xce, 0x7e, 0xf3, 0xcd, 0x8c, 0x0d, 0xfb, 0x99, 0x92, 0x5a, 0x1e, 0x2f, 0x64,
	0x18, 0xcc, 0x8b, 0x38, 0x50, 0x57, 0xc7, 0xa1, 0x4c, 0x43, 0xcc, 0xf4, 0x94, 0x1c, 0x8c, 0xc9,
	0x44, 0x4e, 0x93, 0x3c, 0x9b, 0xae, 0x23, 0xc6, 0x7b, 0x37, 0xdc, 0x49, 0x12, 0x99, 0x96, 0x57,
	0xbc, 0x9f, 0x36, 0x0c, 0x9f, 0x95, 0x49, 0x5e, 0xa4, 0x17, 0x92, 0x31, 0xe8, 0xea, 0xab, 0x0c,
	0xb9, 0xe5, 0x5a, 0x93, 0x5d, 0x9f, 0xce, 0xc6, 0x96, 0x06, 0x09, 0xf2, 0x2d, 0xd7, 0x9a, 0x0c,
	0x7c, 0x3a, 0xb3, 0x11, 0xd8, 0x85, 0x88, 0xb8, 0x4d, 0x26, 0x73, 0x64, 0x0f, 0x60, 0x3b, 0x94,
	0x0b, 0x54, 0xbc, 0x4b, 0xb6, 0x12, 0xb0, 0x87, 0xe0, 0x28, 0x4c, 0x02, 0xf5, 0x85, 0x6f, 0x93,
	0xb9, 0x42, 0x26, 0x5a, 0x07, 0xf3, 0x18, 0xb9, 0x53, 0x46, 0x13, 0xa0, 0xd7, 0x45, 0x82, 0xbc,
	0xe7, 0x5a, 0x13, 0xdb, 0xa7, 0x33, 0xe3, 0xd0, 0x2b, 0xb2, 0x28, 0xd0, 0x18, 0xf1, 0x3e, 0x99,
	0x97, 0xd0, 0x78, 0x42, 0x85, 0xe4, 0x19, 0x94, 0x9e, 0x0a, 0xae, 0x3c, 0x52, 0x71, 0xa0, 0xfc,
	0x4b, 0xc8, 0xc6, 0xd0, 0x97, 0x19, 0x2a, 0x72, 0x0d, 0xc9, 0xb5, 0xc2, 0x86, 0x6b, 0x16, 0x28,
	0x4c, 0x35, 0xdf, 0x29, 0xb9, 0x96, 0xc8, 0x70, 0xcd, 0x43, 0x4c, 0x91, 0xef, 0x92, 0x28, 0x25,
	0x60, 0xfb, 0x00, 0x81, 0xd6, 0x4a, 0xcc, 0x0b, 0x8d, 0x39, 0x3f, 0x70, 0xed, 0xc9, 0xc0, 0xaf,
	0x59, 0xcc, 0x4b, 0x99, 0x12, 0x8b, 0xc0, 0x78, 0x5d, 0xf2, 0xae, 0x30, 0x7b, 0x02, 0xfd, 0xf0,
	0xb3, 0x88, 0x23, 0x85, 0x29, 0x3f, 0x74, 0xed, 0xc9, 0xf0, 0xe4, 0x60, 0xfa, 0x77, 0xef, 0xa6,
	0xb5, 0xc6, 0xf8, 0xab, 0x0b, 0xde, 0x2f, 0x0b, 0x76, 0x7d, 0xbc, 0xac, 0x9c, 0xb3, 0x28, 0x6a,
	0xdd, 0xb4, 0xfb, 0x68, 0xd1, 0x5a, 0xa4, 0xde, 0x35, 0x91, 0xea, 0xc2, 0xf6, 0x37, 0x84, 0x5d,
	0x09, 0x38, 0xa8, 0x09, 0xe8, 0xfd, 0xb0, 0x60, 0xb4, 0xae, 0xe3, 0x2d, 0x35, 0x75, 0x39, 0x57,
	0xd6, 0x7a, 0xae, 0x96, 0xc5, 0x6d, 0xdd, 0x50, 0x9c, 0x7d, 0xe7, 0xe2, 0xea, 0x74, 0x9d, 0x26,
	0xba, 0xbd, 0x3a, 0xdd, 0xaf, 0x44, 0x37, 0x8b, 0xaf, 0xea, 0xeb, 0x72, 0x0a, 0x5d, 0x91, 0x5e,
	0x48, 0xe2, 0xdb, 0xa2, 0x89, 0x14, 0xcc, 0x1e, 0x83, 0x93, 0xeb, 0x40, 0x17, 0x39, 0xd5, 0xd4,
	0x70, 0x8d, 0x9e, 0x3a, 0xa7, 0x30, 0xbf, 0x0a, 0xf7, 0xbe, 0x6f, 0x50, 0x78, 0x29, 0x72, 0x6d,
	0xb4, 0xb8, 0x88, 0x83, 0x4f, 0x95, 0x64, 0x74, 0xbe, 0xf3, 0x0b, 0xa6, 0x9e, 0x58, 0xe4, 0x9a,
	0x0f, 0xdb, 0x0d, 0x25, 0x05, 0x7b, 0xdf, 0x2c, 0xf8, 0xbf, 0x4e, 0x6b, 0xa6, 0xb5, 0xca, 0x69,
	0x07, 0x4b, 0x5c, 0x51, 0x5b, 0xc2, 0xbb, 0xb3, 0xbb, 0xbe, 0x72, 0xc3, 0xcd, 0x95, 0x3b, 0xf9,
	0xdd, 0x85, 0xff, 0x2a, 0x0e, 0xe7, 0xa8, 0x16, 0x22, 0x44, 0x76, 0x0e, 0xce, 0x2c, 0x8a, 0x5e,
	0xa7, 0xc8, 0x0e, 0x6f, 0x7e, 0xa5, 0xb6, 0x47, 0xe3, 0xa3, 0x46, 0x22, 0xb5, 0xa2, 0xbd, 0x0e,
	0x7b, 0x03, 0xce, 0x19, 0x6a, 0x93, 0xb4, 0x81, 0xfa, 0x65, 0x81, 0x39, 0x05, 0xb7, 0x4e, 0xf9,
	0x0a, 0x06, 0x3e, 0x26, 0x72, 0x81, 0xad, 0xb2, 0xee, 0x35, 0x66, 0xbd, 0xc6, 0x70, 0x16, 0xc7,
	0xf7, 0xc0, 0xd0, 0x4c, 0x99, 0xd7, 0x61, 0xef, 0x61, 0xe7, 0x0c, 0xb5, 0xe9, 0x88, 0xc8, 0xb5,
	0x08, 0x1b, 0xf5, 0x34, 0x89, 0x9f, 0x8b, 0x58, 0xa3, 0x1a, 0x7b, 0xb7, 0x36, 0x96, 0xd2, 0x78,
	0x1d, 0xf6, 0x0e, 0x9c, 0x6a, 0xf9, 0x8f, 0x6e, 0x6f, 0x51, 0x19, 0xd5, 0x5a, 0xd2, 0x8f, 0x30,
	0x2a, 0x6f, 0xcc, 0xd6, 0x1f, 0xe5, 0xdb, 0xd4, 0x30, 0x75, 0x8e, 0x1f, 0xfd, 0x2b, 0x39, 0x0d,
	0xb7, 0xd7, 0x79, 0xca, 0x3e, 0x8c, 0x36, 0xff, 0xac, 0x73, 0x87, 0x2c, 0xa7, 0x7f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x18, 0x84, 0x1c, 0x23, 0xa8, 0x07, 0x00, 0x00,
}
