// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/vocabulary/entity.proto

package vocabulary

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EntityInfo struct {
	Brief                *EntityBrief    `protobuf:"bytes,1,opt,name=brief,proto3" json:"brief,omitempty"`
	Properties           []*PropertyInfo `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty"`
	Events               []*EventBrief   `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	Relations            []*VEdgeInfo    `protobuf:"bytes,4,rep,name=relations,proto3" json:"relations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EntityInfo) Reset()         { *m = EntityInfo{} }
func (m *EntityInfo) String() string { return proto.CompactTextString(m) }
func (*EntityInfo) ProtoMessage()    {}
func (*EntityInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{0}
}

func (m *EntityInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityInfo.Unmarshal(m, b)
}
func (m *EntityInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityInfo.Marshal(b, m, deterministic)
}
func (m *EntityInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityInfo.Merge(m, src)
}
func (m *EntityInfo) XXX_Size() int {
	return xxx_messageInfo_EntityInfo.Size(m)
}
func (m *EntityInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EntityInfo proto.InternalMessageInfo

func (m *EntityInfo) GetBrief() *EntityBrief {
	if m != nil {
		return m.Brief
	}
	return nil
}

func (m *EntityInfo) GetProperties() []*PropertyInfo {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *EntityInfo) GetEvents() []*EventBrief {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *EntityInfo) GetRelations() []*VEdgeInfo {
	if m != nil {
		return m.Relations
	}
	return nil
}

type EntityBrief struct {
	Uid                  string          `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner                string          `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Cover                string          `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Concept              string          `protobuf:"bytes,5,opt,name=concept,proto3" json:"concept,omitempty"`
	Add                  string          `protobuf:"bytes,6,opt,name=add,proto3" json:"add,omitempty"`
	Time                 int64           `protobuf:"varint,7,opt,name=time,proto3" json:"time,omitempty"`
	Updated              int64           `protobuf:"varint,8,opt,name=updated,proto3" json:"updated,omitempty"`
	Created              int64           `protobuf:"varint,9,opt,name=created,proto3" json:"created,omitempty"`
	Creator              string          `protobuf:"bytes,10,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string          `protobuf:"bytes,11,opt,name=operator,proto3" json:"operator,omitempty"`
	Mark                 string          `protobuf:"bytes,12,opt,name=mark,proto3" json:"mark,omitempty"`
	Quote                string          `protobuf:"bytes,13,opt,name=quote,proto3" json:"quote,omitempty"`
	Status               uint32          `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"`
	Summary              string          `protobuf:"bytes,15,opt,name=summary,proto3" json:"summary,omitempty"`
	Description          string          `protobuf:"bytes,16,opt,name=description,proto3" json:"description,omitempty"`
	Published            bool            `protobuf:"varint,17,opt,name=published,proto3" json:"published,omitempty"`
	Pushed               int64           `protobuf:"varint,18,opt,name=pushed,proto3" json:"pushed,omitempty"`
	Access               uint32          `protobuf:"varint,19,opt,name=access,proto3" json:"access,omitempty"`
	Score                uint32          `protobuf:"varint,20,opt,name=score,proto3" json:"score,omitempty"`
	Thumb                string          `protobuf:"bytes,21,opt,name=thumb,proto3" json:"thumb,omitempty"`
	Events               uint64          `protobuf:"varint,22,opt,name=events,proto3" json:"events,omitempty"`
	Edges                uint64          `protobuf:"varint,23,opt,name=edges,proto3" json:"edges,omitempty"`
	Synonyms             []string        `protobuf:"bytes,41,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	Tags                 []string        `protobuf:"bytes,42,rep,name=tags,proto3" json:"tags,omitempty"`
	Relates              []string        `protobuf:"bytes,43,rep,name=relates,proto3" json:"relates,omitempty"`
	Links                []string        `protobuf:"bytes,44,rep,name=links,proto3" json:"links,omitempty"`
	Records              []*EntityRecord `protobuf:"bytes,61,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EntityBrief) Reset()         { *m = EntityBrief{} }
func (m *EntityBrief) String() string { return proto.CompactTextString(m) }
func (*EntityBrief) ProtoMessage()    {}
func (*EntityBrief) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{1}
}

func (m *EntityBrief) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityBrief.Unmarshal(m, b)
}
func (m *EntityBrief) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityBrief.Marshal(b, m, deterministic)
}
func (m *EntityBrief) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityBrief.Merge(m, src)
}
func (m *EntityBrief) XXX_Size() int {
	return xxx_messageInfo_EntityBrief.Size(m)
}
func (m *EntityBrief) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityBrief.DiscardUnknown(m)
}

var xxx_messageInfo_EntityBrief proto.InternalMessageInfo

func (m *EntityBrief) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *EntityBrief) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EntityBrief) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *EntityBrief) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *EntityBrief) GetConcept() string {
	if m != nil {
		return m.Concept
	}
	return ""
}

func (m *EntityBrief) GetAdd() string {
	if m != nil {
		return m.Add
	}
	return ""
}

func (m *EntityBrief) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *EntityBrief) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *EntityBrief) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *EntityBrief) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *EntityBrief) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *EntityBrief) GetMark() string {
	if m != nil {
		return m.Mark
	}
	return ""
}

func (m *EntityBrief) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *EntityBrief) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *EntityBrief) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *EntityBrief) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EntityBrief) GetPublished() bool {
	if m != nil {
		return m.Published
	}
	return false
}

func (m *EntityBrief) GetPushed() int64 {
	if m != nil {
		return m.Pushed
	}
	return 0
}

func (m *EntityBrief) GetAccess() uint32 {
	if m != nil {
		return m.Access
	}
	return 0
}

func (m *EntityBrief) GetScore() uint32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *EntityBrief) GetThumb() string {
	if m != nil {
		return m.Thumb
	}
	return ""
}

func (m *EntityBrief) GetEvents() uint64 {
	if m != nil {
		return m.Events
	}
	return 0
}

func (m *EntityBrief) GetEdges() uint64 {
	if m != nil {
		return m.Edges
	}
	return 0
}

func (m *EntityBrief) GetSynonyms() []string {
	if m != nil {
		return m.Synonyms
	}
	return nil
}

func (m *EntityBrief) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *EntityBrief) GetRelates() []string {
	if m != nil {
		return m.Relates
	}
	return nil
}

func (m *EntityBrief) GetLinks() []string {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *EntityBrief) GetRecords() []*EntityRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type EntityRecord struct {
	Option               uint32   `protobuf:"varint,1,opt,name=option,proto3" json:"option,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	From                 string   `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityRecord) Reset()         { *m = EntityRecord{} }
func (m *EntityRecord) String() string { return proto.CompactTextString(m) }
func (*EntityRecord) ProtoMessage()    {}
func (*EntityRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{2}
}

func (m *EntityRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityRecord.Unmarshal(m, b)
}
func (m *EntityRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityRecord.Marshal(b, m, deterministic)
}
func (m *EntityRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityRecord.Merge(m, src)
}
func (m *EntityRecord) XXX_Size() int {
	return xxx_messageInfo_EntityRecord.Size(m)
}
func (m *EntityRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityRecord.DiscardUnknown(m)
}

var xxx_messageInfo_EntityRecord proto.InternalMessageInfo

func (m *EntityRecord) GetOption() uint32 {
	if m != nil {
		return m.Option
	}
	return 0
}

func (m *EntityRecord) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *EntityRecord) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *EntityRecord) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *EntityRecord) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type EventBrief struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Era                  string     `protobuf:"bytes,2,opt,name=era,proto3" json:"era,omitempty"`
	Desc                 string     `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Quote                string     `protobuf:"bytes,4,opt,name=quote,proto3" json:"quote,omitempty"`
	Date                 *DateInfo  `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Place                *PlaceInfo `protobuf:"bytes,6,opt,name=place,proto3" json:"place,omitempty"`
	Uid                  string     `protobuf:"bytes,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Created              int64      `protobuf:"varint,8,opt,name=created,proto3" json:"created,omitempty"`
	Tags                 []string   `protobuf:"bytes,21,rep,name=tags,proto3" json:"tags,omitempty"`
	Assets               []string   `protobuf:"bytes,22,rep,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EventBrief) Reset()         { *m = EventBrief{} }
func (m *EventBrief) String() string { return proto.CompactTextString(m) }
func (*EventBrief) ProtoMessage()    {}
func (*EventBrief) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{3}
}

func (m *EventBrief) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventBrief.Unmarshal(m, b)
}
func (m *EventBrief) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventBrief.Marshal(b, m, deterministic)
}
func (m *EventBrief) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBrief.Merge(m, src)
}
func (m *EventBrief) XXX_Size() int {
	return xxx_messageInfo_EventBrief.Size(m)
}
func (m *EventBrief) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBrief.DiscardUnknown(m)
}

var xxx_messageInfo_EventBrief proto.InternalMessageInfo

func (m *EventBrief) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EventBrief) GetEra() string {
	if m != nil {
		return m.Era
	}
	return ""
}

func (m *EventBrief) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *EventBrief) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *EventBrief) GetDate() *DateInfo {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *EventBrief) GetPlace() *PlaceInfo {
	if m != nil {
		return m.Place
	}
	return nil
}

func (m *EventBrief) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *EventBrief) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *EventBrief) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *EventBrief) GetAssets() []string {
	if m != nil {
		return m.Assets
	}
	return nil
}

type PropertyInfo struct {
	Uid                  string      `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Words                []*WordInfo `protobuf:"bytes,2,rep,name=words,proto3" json:"words,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PropertyInfo) Reset()         { *m = PropertyInfo{} }
func (m *PropertyInfo) String() string { return proto.CompactTextString(m) }
func (*PropertyInfo) ProtoMessage()    {}
func (*PropertyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{4}
}

func (m *PropertyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertyInfo.Unmarshal(m, b)
}
func (m *PropertyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertyInfo.Marshal(b, m, deterministic)
}
func (m *PropertyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertyInfo.Merge(m, src)
}
func (m *PropertyInfo) XXX_Size() int {
	return xxx_messageInfo_PropertyInfo.Size(m)
}
func (m *PropertyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PropertyInfo proto.InternalMessageInfo

func (m *PropertyInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PropertyInfo) GetWords() []*WordInfo {
	if m != nil {
		return m.Words
	}
	return nil
}

type WordInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WordInfo) Reset()         { *m = WordInfo{} }
func (m *WordInfo) String() string { return proto.CompactTextString(m) }
func (*WordInfo) ProtoMessage()    {}
func (*WordInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{5}
}

func (m *WordInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WordInfo.Unmarshal(m, b)
}
func (m *WordInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WordInfo.Marshal(b, m, deterministic)
}
func (m *WordInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WordInfo.Merge(m, src)
}
func (m *WordInfo) XXX_Size() int {
	return xxx_messageInfo_WordInfo.Size(m)
}
func (m *WordInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WordInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WordInfo proto.InternalMessageInfo

func (m *WordInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *WordInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReqEntityAdd struct {
	Creator              string          `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner                string          `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Cover                string          `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Concept              string          `protobuf:"bytes,5,opt,name=concept,proto3" json:"concept,omitempty"`
	Description          string          `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Add                  string          `protobuf:"bytes,7,opt,name=add,proto3" json:"add,omitempty"`
	Summary              string          `protobuf:"bytes,8,opt,name=summary,proto3" json:"summary,omitempty"`
	Mark                 string          `protobuf:"bytes,9,opt,name=mark,proto3" json:"mark,omitempty"`
	Quote                string          `protobuf:"bytes,10,opt,name=quote,proto3" json:"quote,omitempty"`
	Status               uint32          `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	Synonyms             []string        `protobuf:"bytes,21,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	Tags                 []string        `protobuf:"bytes,22,rep,name=tags,proto3" json:"tags,omitempty"`
	Relates              []string        `protobuf:"bytes,23,rep,name=relates,proto3" json:"relates,omitempty"`
	Properties           []*PropertyInfo `protobuf:"bytes,41,rep,name=properties,proto3" json:"properties,omitempty"`
	Events               []*EventBrief   `protobuf:"bytes,42,rep,name=events,proto3" json:"events,omitempty"`
	Relations            []*VEdgeInfo    `protobuf:"bytes,43,rep,name=relations,proto3" json:"relations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReqEntityAdd) Reset()         { *m = ReqEntityAdd{} }
func (m *ReqEntityAdd) String() string { return proto.CompactTextString(m) }
func (*ReqEntityAdd) ProtoMessage()    {}
func (*ReqEntityAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{6}
}

func (m *ReqEntityAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEntityAdd.Unmarshal(m, b)
}
func (m *ReqEntityAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEntityAdd.Marshal(b, m, deterministic)
}
func (m *ReqEntityAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEntityAdd.Merge(m, src)
}
func (m *ReqEntityAdd) XXX_Size() int {
	return xxx_messageInfo_ReqEntityAdd.Size(m)
}
func (m *ReqEntityAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEntityAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEntityAdd proto.InternalMessageInfo

func (m *ReqEntityAdd) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ReqEntityAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqEntityAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqEntityAdd) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ReqEntityAdd) GetConcept() string {
	if m != nil {
		return m.Concept
	}
	return ""
}

func (m *ReqEntityAdd) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ReqEntityAdd) GetAdd() string {
	if m != nil {
		return m.Add
	}
	return ""
}

func (m *ReqEntityAdd) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *ReqEntityAdd) GetMark() string {
	if m != nil {
		return m.Mark
	}
	return ""
}

func (m *ReqEntityAdd) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *ReqEntityAdd) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReqEntityAdd) GetSynonyms() []string {
	if m != nil {
		return m.Synonyms
	}
	return nil
}

func (m *ReqEntityAdd) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ReqEntityAdd) GetRelates() []string {
	if m != nil {
		return m.Relates
	}
	return nil
}

func (m *ReqEntityAdd) GetProperties() []*PropertyInfo {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *ReqEntityAdd) GetEvents() []*EventBrief {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *ReqEntityAdd) GetRelations() []*VEdgeInfo {
	if m != nil {
		return m.Relations
	}
	return nil
}

type ReqEntityStatic struct {
	Uid                  string          `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string          `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Add                  string          `protobuf:"bytes,4,opt,name=add,proto3" json:"add,omitempty"`
	Concept              string          `protobuf:"bytes,5,opt,name=concept,proto3" json:"concept,omitempty"`
	Cover                string          `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty"`
	Operator             string          `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Summary              string          `protobuf:"bytes,8,opt,name=summary,proto3" json:"summary,omitempty"`
	Mark                 string          `protobuf:"bytes,9,opt,name=mark,proto3" json:"mark,omitempty"`
	Quote                string          `protobuf:"bytes,10,opt,name=quote,proto3" json:"quote,omitempty"`
	Synonyms             []string        `protobuf:"bytes,21,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	Tags                 []string        `protobuf:"bytes,22,rep,name=tags,proto3" json:"tags,omitempty"`
	Properties           []*PropertyInfo `protobuf:"bytes,31,rep,name=properties,proto3" json:"properties,omitempty"`
	Relations            []*VEdgeInfo    `protobuf:"bytes,32,rep,name=relations,proto3" json:"relations,omitempty"`
	Events               []*EventBrief   `protobuf:"bytes,33,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReqEntityStatic) Reset()         { *m = ReqEntityStatic{} }
func (m *ReqEntityStatic) String() string { return proto.CompactTextString(m) }
func (*ReqEntityStatic) ProtoMessage()    {}
func (*ReqEntityStatic) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{7}
}

func (m *ReqEntityStatic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEntityStatic.Unmarshal(m, b)
}
func (m *ReqEntityStatic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEntityStatic.Marshal(b, m, deterministic)
}
func (m *ReqEntityStatic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEntityStatic.Merge(m, src)
}
func (m *ReqEntityStatic) XXX_Size() int {
	return xxx_messageInfo_ReqEntityStatic.Size(m)
}
func (m *ReqEntityStatic) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEntityStatic.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEntityStatic proto.InternalMessageInfo

func (m *ReqEntityStatic) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqEntityStatic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqEntityStatic) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ReqEntityStatic) GetAdd() string {
	if m != nil {
		return m.Add
	}
	return ""
}

func (m *ReqEntityStatic) GetConcept() string {
	if m != nil {
		return m.Concept
	}
	return ""
}

func (m *ReqEntityStatic) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ReqEntityStatic) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqEntityStatic) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *ReqEntityStatic) GetMark() string {
	if m != nil {
		return m.Mark
	}
	return ""
}

func (m *ReqEntityStatic) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *ReqEntityStatic) GetSynonyms() []string {
	if m != nil {
		return m.Synonyms
	}
	return nil
}

func (m *ReqEntityStatic) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ReqEntityStatic) GetProperties() []*PropertyInfo {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *ReqEntityStatic) GetRelations() []*VEdgeInfo {
	if m != nil {
		return m.Relations
	}
	return nil
}

func (m *ReqEntityStatic) GetEvents() []*EventBrief {
	if m != nil {
		return m.Events
	}
	return nil
}

type ReqEntityRelations struct {
	Uid                  string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string       `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Relations            []*VEdgeInfo `protobuf:"bytes,11,rep,name=relations,proto3" json:"relations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReqEntityRelations) Reset()         { *m = ReqEntityRelations{} }
func (m *ReqEntityRelations) String() string { return proto.CompactTextString(m) }
func (*ReqEntityRelations) ProtoMessage()    {}
func (*ReqEntityRelations) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{8}
}

func (m *ReqEntityRelations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEntityRelations.Unmarshal(m, b)
}
func (m *ReqEntityRelations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEntityRelations.Marshal(b, m, deterministic)
}
func (m *ReqEntityRelations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEntityRelations.Merge(m, src)
}
func (m *ReqEntityRelations) XXX_Size() int {
	return xxx_messageInfo_ReqEntityRelations.Size(m)
}
func (m *ReqEntityRelations) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEntityRelations.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEntityRelations proto.InternalMessageInfo

func (m *ReqEntityRelations) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqEntityRelations) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqEntityRelations) GetRelations() []*VEdgeInfo {
	if m != nil {
		return m.Relations
	}
	return nil
}

type ReqEntityEvents struct {
	Uid                  string        `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string        `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Events               []*EventBrief `protobuf:"bytes,15,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReqEntityEvents) Reset()         { *m = ReqEntityEvents{} }
func (m *ReqEntityEvents) String() string { return proto.CompactTextString(m) }
func (*ReqEntityEvents) ProtoMessage()    {}
func (*ReqEntityEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{9}
}

func (m *ReqEntityEvents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEntityEvents.Unmarshal(m, b)
}
func (m *ReqEntityEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEntityEvents.Marshal(b, m, deterministic)
}
func (m *ReqEntityEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEntityEvents.Merge(m, src)
}
func (m *ReqEntityEvents) XXX_Size() int {
	return xxx_messageInfo_ReqEntityEvents.Size(m)
}
func (m *ReqEntityEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEntityEvents.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEntityEvents proto.InternalMessageInfo

func (m *ReqEntityEvents) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqEntityEvents) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqEntityEvents) GetEvents() []*EventBrief {
	if m != nil {
		return m.Events
	}
	return nil
}

type ReqEntityBy struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Number               int32    `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Page                 int32    `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Concept              string   `protobuf:"bytes,5,opt,name=concept,proto3" json:"concept,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqEntityBy) Reset()         { *m = ReqEntityBy{} }
func (m *ReqEntityBy) String() string { return proto.CompactTextString(m) }
func (*ReqEntityBy) ProtoMessage()    {}
func (*ReqEntityBy) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{10}
}

func (m *ReqEntityBy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEntityBy.Unmarshal(m, b)
}
func (m *ReqEntityBy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEntityBy.Marshal(b, m, deterministic)
}
func (m *ReqEntityBy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEntityBy.Merge(m, src)
}
func (m *ReqEntityBy) XXX_Size() int {
	return xxx_messageInfo_ReqEntityBy.Size(m)
}
func (m *ReqEntityBy) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEntityBy.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEntityBy proto.InternalMessageInfo

func (m *ReqEntityBy) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReqEntityBy) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqEntityBy) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReqEntityBy) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReqEntityBy) GetConcept() string {
	if m != nil {
		return m.Concept
	}
	return ""
}

type ReqEntityByProp struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqEntityByProp) Reset()         { *m = ReqEntityByProp{} }
func (m *ReqEntityByProp) String() string { return proto.CompactTextString(m) }
func (*ReqEntityByProp) ProtoMessage()    {}
func (*ReqEntityByProp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{11}
}

func (m *ReqEntityByProp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEntityByProp.Unmarshal(m, b)
}
func (m *ReqEntityByProp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEntityByProp.Marshal(b, m, deterministic)
}
func (m *ReqEntityByProp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEntityByProp.Merge(m, src)
}
func (m *ReqEntityByProp) XXX_Size() int {
	return xxx_messageInfo_ReqEntityByProp.Size(m)
}
func (m *ReqEntityByProp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEntityByProp.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEntityByProp proto.InternalMessageInfo

func (m *ReqEntityByProp) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqEntityByProp) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ReplyEntityInfo struct {
	Info                 *EntityInfo  `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyEntityInfo) Reset()         { *m = ReplyEntityInfo{} }
func (m *ReplyEntityInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyEntityInfo) ProtoMessage()    {}
func (*ReplyEntityInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{12}
}

func (m *ReplyEntityInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyEntityInfo.Unmarshal(m, b)
}
func (m *ReplyEntityInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyEntityInfo.Marshal(b, m, deterministic)
}
func (m *ReplyEntityInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyEntityInfo.Merge(m, src)
}
func (m *ReplyEntityInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyEntityInfo.Size(m)
}
func (m *ReplyEntityInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyEntityInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyEntityInfo proto.InternalMessageInfo

func (m *ReplyEntityInfo) GetInfo() *EntityInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyEntityInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyEntityBrief struct {
	Info                 *EntityBrief `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyEntityBrief) Reset()         { *m = ReplyEntityBrief{} }
func (m *ReplyEntityBrief) String() string { return proto.CompactTextString(m) }
func (*ReplyEntityBrief) ProtoMessage()    {}
func (*ReplyEntityBrief) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{13}
}

func (m *ReplyEntityBrief) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyEntityBrief.Unmarshal(m, b)
}
func (m *ReplyEntityBrief) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyEntityBrief.Marshal(b, m, deterministic)
}
func (m *ReplyEntityBrief) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyEntityBrief.Merge(m, src)
}
func (m *ReplyEntityBrief) XXX_Size() int {
	return xxx_messageInfo_ReplyEntityBrief.Size(m)
}
func (m *ReplyEntityBrief) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyEntityBrief.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyEntityBrief proto.InternalMessageInfo

func (m *ReplyEntityBrief) GetInfo() *EntityBrief {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyEntityBrief) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyEntityList struct {
	Status               *ReplyStatus  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint32        `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page                 uint32        `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Flag                 string        `protobuf:"bytes,4,opt,name=flag,proto3" json:"flag,omitempty"`
	List                 []*EntityInfo `protobuf:"bytes,11,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReplyEntityList) Reset()         { *m = ReplyEntityList{} }
func (m *ReplyEntityList) String() string { return proto.CompactTextString(m) }
func (*ReplyEntityList) ProtoMessage()    {}
func (*ReplyEntityList) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{14}
}

func (m *ReplyEntityList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyEntityList.Unmarshal(m, b)
}
func (m *ReplyEntityList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyEntityList.Marshal(b, m, deterministic)
}
func (m *ReplyEntityList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyEntityList.Merge(m, src)
}
func (m *ReplyEntityList) XXX_Size() int {
	return xxx_messageInfo_ReplyEntityList.Size(m)
}
func (m *ReplyEntityList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyEntityList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyEntityList proto.InternalMessageInfo

func (m *ReplyEntityList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyEntityList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyEntityList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplyEntityList) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

func (m *ReplyEntityList) GetList() []*EntityInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyEntityPublic struct {
	Status               *ReplyStatus  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Systems              []*EntityInfo `protobuf:"bytes,11,rep,name=systems,proto3" json:"systems,omitempty"`
	Users                []*EntityInfo `protobuf:"bytes,12,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReplyEntityPublic) Reset()         { *m = ReplyEntityPublic{} }
func (m *ReplyEntityPublic) String() string { return proto.CompactTextString(m) }
func (*ReplyEntityPublic) ProtoMessage()    {}
func (*ReplyEntityPublic) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{15}
}

func (m *ReplyEntityPublic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyEntityPublic.Unmarshal(m, b)
}
func (m *ReplyEntityPublic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyEntityPublic.Marshal(b, m, deterministic)
}
func (m *ReplyEntityPublic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyEntityPublic.Merge(m, src)
}
func (m *ReplyEntityPublic) XXX_Size() int {
	return xxx_messageInfo_ReplyEntityPublic.Size(m)
}
func (m *ReplyEntityPublic) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyEntityPublic.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyEntityPublic proto.InternalMessageInfo

func (m *ReplyEntityPublic) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyEntityPublic) GetSystems() []*EntityInfo {
	if m != nil {
		return m.Systems
	}
	return nil
}

func (m *ReplyEntityPublic) GetUsers() []*EntityInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

type ReqEntityProperty struct {
	Uid                  string        `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Property             *PropertyInfo `protobuf:"bytes,2,opt,name=property,proto3" json:"property,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReqEntityProperty) Reset()         { *m = ReqEntityProperty{} }
func (m *ReqEntityProperty) String() string { return proto.CompactTextString(m) }
func (*ReqEntityProperty) ProtoMessage()    {}
func (*ReqEntityProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{16}
}

func (m *ReqEntityProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEntityProperty.Unmarshal(m, b)
}
func (m *ReqEntityProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEntityProperty.Marshal(b, m, deterministic)
}
func (m *ReqEntityProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEntityProperty.Merge(m, src)
}
func (m *ReqEntityProperty) XXX_Size() int {
	return xxx_messageInfo_ReqEntityProperty.Size(m)
}
func (m *ReqEntityProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEntityProperty.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEntityProperty proto.InternalMessageInfo

func (m *ReqEntityProperty) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqEntityProperty) GetProperty() *PropertyInfo {
	if m != nil {
		return m.Property
	}
	return nil
}

type ReqEntityProperties struct {
	Uid                  string          `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string          `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Properties           []*PropertyInfo `protobuf:"bytes,11,rep,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReqEntityProperties) Reset()         { *m = ReqEntityProperties{} }
func (m *ReqEntityProperties) String() string { return proto.CompactTextString(m) }
func (*ReqEntityProperties) ProtoMessage()    {}
func (*ReqEntityProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{17}
}

func (m *ReqEntityProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEntityProperties.Unmarshal(m, b)
}
func (m *ReqEntityProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEntityProperties.Marshal(b, m, deterministic)
}
func (m *ReqEntityProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEntityProperties.Merge(m, src)
}
func (m *ReqEntityProperties) XXX_Size() int {
	return xxx_messageInfo_ReqEntityProperties.Size(m)
}
func (m *ReqEntityProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEntityProperties.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEntityProperties proto.InternalMessageInfo

func (m *ReqEntityProperties) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqEntityProperties) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqEntityProperties) GetProperties() []*PropertyInfo {
	if m != nil {
		return m.Properties
	}
	return nil
}

type ReqEntitySearch struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner                string   `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Concept              []string `protobuf:"bytes,11,rep,name=concept,proto3" json:"concept,omitempty"`
	Attribute            []string `protobuf:"bytes,12,rep,name=attribute,proto3" json:"attribute,omitempty"`
	Tags                 []string `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqEntitySearch) Reset()         { *m = ReqEntitySearch{} }
func (m *ReqEntitySearch) String() string { return proto.CompactTextString(m) }
func (*ReqEntitySearch) ProtoMessage()    {}
func (*ReqEntitySearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{18}
}

func (m *ReqEntitySearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEntitySearch.Unmarshal(m, b)
}
func (m *ReqEntitySearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEntitySearch.Marshal(b, m, deterministic)
}
func (m *ReqEntitySearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEntitySearch.Merge(m, src)
}
func (m *ReqEntitySearch) XXX_Size() int {
	return xxx_messageInfo_ReqEntitySearch.Size(m)
}
func (m *ReqEntitySearch) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEntitySearch.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEntitySearch proto.InternalMessageInfo

func (m *ReqEntitySearch) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReqEntitySearch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqEntitySearch) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqEntitySearch) GetConcept() []string {
	if m != nil {
		return m.Concept
	}
	return nil
}

func (m *ReqEntitySearch) GetAttribute() []string {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *ReqEntitySearch) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReqEntityMatch struct {
	Keywords             string   `protobuf:"bytes,1,opt,name=keywords,proto3" json:"keywords,omitempty"`
	Number               int32    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Owner                string   `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqEntityMatch) Reset()         { *m = ReqEntityMatch{} }
func (m *ReqEntityMatch) String() string { return proto.CompactTextString(m) }
func (*ReqEntityMatch) ProtoMessage()    {}
func (*ReqEntityMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{19}
}

func (m *ReqEntityMatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEntityMatch.Unmarshal(m, b)
}
func (m *ReqEntityMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEntityMatch.Marshal(b, m, deterministic)
}
func (m *ReqEntityMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEntityMatch.Merge(m, src)
}
func (m *ReqEntityMatch) XXX_Size() int {
	return xxx_messageInfo_ReqEntityMatch.Size(m)
}
func (m *ReqEntityMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEntityMatch.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEntityMatch proto.InternalMessageInfo

func (m *ReqEntityMatch) GetKeywords() string {
	if m != nil {
		return m.Keywords
	}
	return ""
}

func (m *ReqEntityMatch) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReqEntityMatch) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReqEntityMatch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqEntityMatch) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type ReplyEntityProperties struct {
	Uid                  string          `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Updated              uint64          `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Status               *ReplyStatus    `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Properties           []*PropertyInfo `protobuf:"bytes,11,rep,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReplyEntityProperties) Reset()         { *m = ReplyEntityProperties{} }
func (m *ReplyEntityProperties) String() string { return proto.CompactTextString(m) }
func (*ReplyEntityProperties) ProtoMessage()    {}
func (*ReplyEntityProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{20}
}

func (m *ReplyEntityProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyEntityProperties.Unmarshal(m, b)
}
func (m *ReplyEntityProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyEntityProperties.Marshal(b, m, deterministic)
}
func (m *ReplyEntityProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyEntityProperties.Merge(m, src)
}
func (m *ReplyEntityProperties) XXX_Size() int {
	return xxx_messageInfo_ReplyEntityProperties.Size(m)
}
func (m *ReplyEntityProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyEntityProperties.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyEntityProperties proto.InternalMessageInfo

func (m *ReplyEntityProperties) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyEntityProperties) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ReplyEntityProperties) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyEntityProperties) GetProperties() []*PropertyInfo {
	if m != nil {
		return m.Properties
	}
	return nil
}

type ReqEntityBase struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Add                  string   `protobuf:"bytes,4,opt,name=add,proto3" json:"add,omitempty"`
	Concept              string   `protobuf:"bytes,5,opt,name=concept,proto3" json:"concept,omitempty"`
	Cover                string   `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty"`
	Operator             string   `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Summary              string   `protobuf:"bytes,8,opt,name=summary,proto3" json:"summary,omitempty"`
	Mark                 string   `protobuf:"bytes,9,opt,name=mark,proto3" json:"mark,omitempty"`
	Quote                string   `protobuf:"bytes,10,opt,name=quote,proto3" json:"quote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqEntityBase) Reset()         { *m = ReqEntityBase{} }
func (m *ReqEntityBase) String() string { return proto.CompactTextString(m) }
func (*ReqEntityBase) ProtoMessage()    {}
func (*ReqEntityBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{21}
}

func (m *ReqEntityBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEntityBase.Unmarshal(m, b)
}
func (m *ReqEntityBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEntityBase.Marshal(b, m, deterministic)
}
func (m *ReqEntityBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEntityBase.Merge(m, src)
}
func (m *ReqEntityBase) XXX_Size() int {
	return xxx_messageInfo_ReqEntityBase.Size(m)
}
func (m *ReqEntityBase) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEntityBase.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEntityBase proto.InternalMessageInfo

func (m *ReqEntityBase) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqEntityBase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqEntityBase) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ReqEntityBase) GetAdd() string {
	if m != nil {
		return m.Add
	}
	return ""
}

func (m *ReqEntityBase) GetConcept() string {
	if m != nil {
		return m.Concept
	}
	return ""
}

func (m *ReqEntityBase) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ReqEntityBase) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqEntityBase) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *ReqEntityBase) GetMark() string {
	if m != nil {
		return m.Mark
	}
	return ""
}

func (m *ReqEntityBase) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

type ReqEntityStatus struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Status               uint32   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Remark               string   `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqEntityStatus) Reset()         { *m = ReqEntityStatus{} }
func (m *ReqEntityStatus) String() string { return proto.CompactTextString(m) }
func (*ReqEntityStatus) ProtoMessage()    {}
func (*ReqEntityStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{22}
}

func (m *ReqEntityStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEntityStatus.Unmarshal(m, b)
}
func (m *ReqEntityStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEntityStatus.Marshal(b, m, deterministic)
}
func (m *ReqEntityStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEntityStatus.Merge(m, src)
}
func (m *ReqEntityStatus) XXX_Size() int {
	return xxx_messageInfo_ReqEntityStatus.Size(m)
}
func (m *ReqEntityStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEntityStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEntityStatus proto.InternalMessageInfo

func (m *ReqEntityStatus) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqEntityStatus) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqEntityStatus) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReqEntityStatus) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type ReplyEntityStatus struct {
	Uid                  string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	State                uint32       `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Updated              uint64       `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyEntityStatus) Reset()         { *m = ReplyEntityStatus{} }
func (m *ReplyEntityStatus) String() string { return proto.CompactTextString(m) }
func (*ReplyEntityStatus) ProtoMessage()    {}
func (*ReplyEntityStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{23}
}

func (m *ReplyEntityStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyEntityStatus.Unmarshal(m, b)
}
func (m *ReplyEntityStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyEntityStatus.Marshal(b, m, deterministic)
}
func (m *ReplyEntityStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyEntityStatus.Merge(m, src)
}
func (m *ReplyEntityStatus) XXX_Size() int {
	return xxx_messageInfo_ReplyEntityStatus.Size(m)
}
func (m *ReplyEntityStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyEntityStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyEntityStatus proto.InternalMessageInfo

func (m *ReplyEntityStatus) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyEntityStatus) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *ReplyEntityStatus) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyEntityStatus) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type ReplyEntityUpdate struct {
	Uid                  string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Updated              uint64       `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	List                 []string     `protobuf:"bytes,11,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyEntityUpdate) Reset()         { *m = ReplyEntityUpdate{} }
func (m *ReplyEntityUpdate) String() string { return proto.CompactTextString(m) }
func (*ReplyEntityUpdate) ProtoMessage()    {}
func (*ReplyEntityUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db6b7e83369e528, []int{24}
}

func (m *ReplyEntityUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyEntityUpdate.Unmarshal(m, b)
}
func (m *ReplyEntityUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyEntityUpdate.Marshal(b, m, deterministic)
}
func (m *ReplyEntityUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyEntityUpdate.Merge(m, src)
}
func (m *ReplyEntityUpdate) XXX_Size() int {
	return xxx_messageInfo_ReplyEntityUpdate.Size(m)
}
func (m *ReplyEntityUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyEntityUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyEntityUpdate proto.InternalMessageInfo

func (m *ReplyEntityUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyEntityUpdate) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ReplyEntityUpdate) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyEntityUpdate) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*EntityInfo)(nil), "omo.msp.vocabulary.EntityInfo")
	proto.RegisterType((*EntityBrief)(nil), "omo.msp.vocabulary.EntityBrief")
	proto.RegisterType((*EntityRecord)(nil), "omo.msp.vocabulary.EntityRecord")
	proto.RegisterType((*EventBrief)(nil), "omo.msp.vocabulary.EventBrief")
	proto.RegisterType((*PropertyInfo)(nil), "omo.msp.vocabulary.PropertyInfo")
	proto.RegisterType((*WordInfo)(nil), "omo.msp.vocabulary.WordInfo")
	proto.RegisterType((*ReqEntityAdd)(nil), "omo.msp.vocabulary.ReqEntityAdd")
	proto.RegisterType((*ReqEntityStatic)(nil), "omo.msp.vocabulary.ReqEntityStatic")
	proto.RegisterType((*ReqEntityRelations)(nil), "omo.msp.vocabulary.ReqEntityRelations")
	proto.RegisterType((*ReqEntityEvents)(nil), "omo.msp.vocabulary.ReqEntityEvents")
	proto.RegisterType((*ReqEntityBy)(nil), "omo.msp.vocabulary.ReqEntityBy")
	proto.RegisterType((*ReqEntityByProp)(nil), "omo.msp.vocabulary.ReqEntityByProp")
	proto.RegisterType((*ReplyEntityInfo)(nil), "omo.msp.vocabulary.ReplyEntityInfo")
	proto.RegisterType((*ReplyEntityBrief)(nil), "omo.msp.vocabulary.ReplyEntityBrief")
	proto.RegisterType((*ReplyEntityList)(nil), "omo.msp.vocabulary.ReplyEntityList")
	proto.RegisterType((*ReplyEntityPublic)(nil), "omo.msp.vocabulary.ReplyEntityPublic")
	proto.RegisterType((*ReqEntityProperty)(nil), "omo.msp.vocabulary.ReqEntityProperty")
	proto.RegisterType((*ReqEntityProperties)(nil), "omo.msp.vocabulary.ReqEntityProperties")
	proto.RegisterType((*ReqEntitySearch)(nil), "omo.msp.vocabulary.ReqEntitySearch")
	proto.RegisterType((*ReqEntityMatch)(nil), "omo.msp.vocabulary.ReqEntityMatch")
	proto.RegisterType((*ReplyEntityProperties)(nil), "omo.msp.vocabulary.ReplyEntityProperties")
	proto.RegisterType((*ReqEntityBase)(nil), "omo.msp.vocabulary.ReqEntityBase")
	proto.RegisterType((*ReqEntityStatus)(nil), "omo.msp.vocabulary.ReqEntityStatus")
	proto.RegisterType((*ReplyEntityStatus)(nil), "omo.msp.vocabulary.ReplyEntityStatus")
	proto.RegisterType((*ReplyEntityUpdate)(nil), "omo.msp.vocabulary.ReplyEntityUpdate")
}

func init() {
	proto.RegisterFile("proto/vocabulary/entity.proto", fileDescriptor_3db6b7e83369e528)
}

var fileDescriptor_3db6b7e83369e528 = []byte{
	// 1798 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x59, 0x4b, 0x6f, 0xdb, 0xd8,
	0x15, 0x36, 0xf5, 0xb2, 0x74, 0x24, 0xd9, 0x0e, 0x13, 0x3b, 0x84, 0x91, 0x87, 0xc2, 0x34, 0xad,
	0x93, 0x14, 0x4e, 0xe0, 0xf4, 0xfd, 0x00, 0x6a, 0xb5, 0xa9, 0x51, 0xa0, 0x69, 0x5c, 0x39, 0x4d,
	0x0a, 0xb7, 0x8b, 0x52, 0xe4, 0xb5, 0x4d, 0x58, 0x12, 0x15, 0xde, 0x4b, 0xa7, 0xdc, 0xf4, 0x05,
	0x74, 0x57, 0x74, 0xd3, 0x65, 0x17, 0xfd, 0x23, 0xc5, 0xec, 0x07, 0xb3, 0x9d, 0x7f, 0x31, 0xff,
	0x60, 0x56, 0x83, 0x73, 0x2e, 0x1f, 0x97, 0xb6, 0x24, 0x92, 0xb6, 0x67, 0x16, 0xb3, 0xe3, 0xb9,
	0x3a, 0xf7, 0xbc, 0xcf, 0x77, 0xce, 0xb5, 0xe1, 0xee, 0xd4, 0xf7, 0x84, 0xf7, 0xec, 0xcc, 0xb3,
	0xad, 0x61, 0x30, 0xb2, 0xfc, 0xf0, 0x19, 0x9b, 0x08, 0x57, 0x84, 0xdb, 0x74, 0xae, 0xeb, 0xde,
	0xd8, 0xdb, 0x1e, 0xf3, 0xe9, 0x76, 0xca, 0xb0, 0x79, 0xf1, 0x8a, 0xed, 0x8d, 0xc7, 0xde, 0x44,
	0x5e, 0x31, 0x3f, 0xd7, 0x00, 0x5e, 0x92, 0x8c, 0x5f, 0x4d, 0x8e, 0x3c, 0xfd, 0xbb, 0x50, 0x1f,
	0xfa, 0x2e, 0x3b, 0x32, 0xb4, 0x9e, 0xb6, 0xd5, 0xde, 0xb9, 0xbf, 0x7d, 0x51, 0xe2, 0xb6, 0x64,
	0xef, 0x23, 0xdb, 0x40, 0x72, 0xeb, 0x3f, 0x03, 0x98, 0xfa, 0xde, 0x94, 0xf9, 0xc2, 0x65, 0xdc,
	0xa8, 0xf4, 0xaa, 0x5b, 0xed, 0x9d, 0xde, 0xac, 0xbb, 0xfb, 0x92, 0x8b, 0x94, 0x0d, 0x94, 0x3b,
	0xfa, 0xf7, 0xa0, 0xc1, 0xce, 0xd8, 0x44, 0x70, 0xa3, 0x4a, 0xb7, 0xef, 0xcd, 0xd4, 0x8c, 0x1c,
	0x52, 0x71, 0xc4, 0xad, 0xff, 0x18, 0x5a, 0x3e, 0x1b, 0x59, 0xc2, 0xf5, 0x26, 0xdc, 0xa8, 0xd1,
	0xd5, 0xbb, 0xb3, 0xae, 0xbe, 0x7d, 0xe9, 0x1c, 0x33, 0xd2, 0x9a, 0xf2, 0x9b, 0x9f, 0xd4, 0xa1,
	0xad, 0x78, 0xa3, 0xaf, 0x41, 0x35, 0x70, 0x1d, 0xf2, 0xbd, 0x35, 0xc0, 0x4f, 0x5d, 0x87, 0xda,
	0xc4, 0x1a, 0x33, 0xa3, 0x42, 0x47, 0xf4, 0xad, 0xdf, 0x82, 0xba, 0xf7, 0x61, 0xc2, 0x7c, 0xa3,
	0x4a, 0x87, 0x92, 0xc0, 0x53, 0xdb, 0x3b, 0x63, 0xbe, 0x51, 0x93, 0xa7, 0x44, 0xe8, 0x06, 0x2c,
	0xdb, 0xde, 0xc4, 0x66, 0x53, 0x61, 0xd4, 0xe9, 0x3c, 0x26, 0x51, 0x97, 0xe5, 0x38, 0x46, 0x43,
	0xea, 0xb2, 0x1c, 0xd2, 0x25, 0xdc, 0x31, 0x33, 0x96, 0x7b, 0xda, 0x56, 0x75, 0x40, 0xdf, 0x78,
	0x3f, 0x98, 0x3a, 0x96, 0x60, 0x8e, 0xd1, 0xa4, 0xe3, 0x98, 0x24, 0xc9, 0x3e, 0xa3, 0x5f, 0x5a,
	0xf2, 0x97, 0x88, 0x4c, 0x7e, 0xf1, 0x7c, 0x03, 0x22, 0x9d, 0x92, 0xd4, 0x37, 0xa1, 0x89, 0x01,
	0xa7, 0x9f, 0xda, 0xf4, 0x53, 0x42, 0xa3, 0xf6, 0xb1, 0xe5, 0x9f, 0x1a, 0x1d, 0xe9, 0x29, 0x7e,
	0xa3, 0x4f, 0xef, 0x03, 0x4f, 0x30, 0xa3, 0x2b, 0x7d, 0x22, 0x42, 0xdf, 0x80, 0x06, 0x17, 0x96,
	0x08, 0xb8, 0xb1, 0xd2, 0xd3, 0xb6, 0xba, 0x83, 0x88, 0x42, 0xbd, 0x3c, 0x18, 0x8f, 0x2d, 0x3f,
	0x34, 0x56, 0xa5, 0xde, 0x88, 0xd4, 0x7b, 0xd0, 0x76, 0x18, 0xb7, 0x7d, 0x77, 0x8a, 0x71, 0x37,
	0xd6, 0xe8, 0x57, 0xf5, 0x48, 0xbf, 0x03, 0xad, 0x69, 0x30, 0x1c, 0xb9, 0xfc, 0x84, 0x39, 0xc6,
	0x8d, 0x9e, 0xb6, 0xd5, 0x1c, 0xa4, 0x07, 0xa8, 0x71, 0x1a, 0xd0, 0x4f, 0x3a, 0xb9, 0x1a, 0x51,
	0x78, 0x6e, 0xd9, 0x36, 0xe3, 0xdc, 0xb8, 0x29, 0x2d, 0x91, 0x14, 0xda, 0xcd, 0x6d, 0xcf, 0x67,
	0xc6, 0x2d, 0x3a, 0x96, 0x04, 0x9e, 0x8a, 0x93, 0x60, 0x3c, 0x34, 0xd6, 0xa5, 0x37, 0x44, 0xa0,
	0x8c, 0xa8, 0xf0, 0x36, 0x7a, 0xda, 0x56, 0x2d, 0x29, 0xac, 0x5b, 0x50, 0x67, 0xce, 0x31, 0xe3,
	0xc6, 0x6d, 0x3a, 0x96, 0x04, 0x46, 0x90, 0x87, 0x13, 0x6f, 0x12, 0x8e, 0xb9, 0xf1, 0xb8, 0x57,
	0xc5, 0x08, 0xc6, 0x34, 0xe5, 0xcf, 0x3a, 0xe6, 0xc6, 0x13, 0x3a, 0xa7, 0x6f, 0x8c, 0x09, 0x95,
	0x1b, 0xe3, 0xc6, 0x53, 0x3a, 0x8e, 0x49, 0x94, 0x3f, 0x72, 0x27, 0xa7, 0xdc, 0xf8, 0x36, 0x9d,
	0x4b, 0x42, 0xff, 0x11, 0xf2, 0xdb, 0x9e, 0xef, 0x70, 0xe3, 0xa7, 0xf3, 0xbb, 0x48, 0xd6, 0xec,
	0x80, 0x18, 0x07, 0xf1, 0x05, 0xf3, 0x0c, 0x3a, 0xea, 0x0f, 0xe8, 0x99, 0x27, 0x03, 0xae, 0xc9,
	0xe8, 0x48, 0x0a, 0xed, 0x0c, 0x38, 0xf3, 0xe3, 0x9a, 0xc6, 0x6f, 0xe4, 0xf5, 0x19, 0xe5, 0x5f,
	0x16, 0x75, 0x44, 0x21, 0xef, 0x91, 0xef, 0x8d, 0xa3, 0xa2, 0xa6, 0x6f, 0x7d, 0x05, 0x2a, 0xc2,
	0x8b, 0xca, 0xb9, 0x22, 0x3c, 0xf3, 0xbf, 0x15, 0x80, 0xb4, 0x33, 0x93, 0x96, 0xd1, 0x94, 0x96,
	0x59, 0x83, 0x2a, 0xf3, 0xad, 0x48, 0x23, 0x7e, 0x22, 0x17, 0xe6, 0x3f, 0x52, 0x47, 0xdf, 0x69,
	0xb9, 0xd5, 0xd4, 0x72, 0x7b, 0x0e, 0x35, 0xac, 0x78, 0x52, 0xd8, 0xde, 0xb9, 0x33, 0x2b, 0x1e,
	0xbf, 0xb0, 0x84, 0xec, 0x6d, 0xe2, 0xd4, 0x5f, 0x40, 0x7d, 0x3a, 0xb2, 0x6c, 0x46, 0xcd, 0x35,
	0x07, 0x0f, 0xf6, 0x91, 0x81, 0xee, 0x48, 0xde, 0xb8, 0xf7, 0x97, 0xd3, 0xde, 0x57, 0x3a, 0xac,
	0x99, 0xed, 0xb0, 0x38, 0xd3, 0xeb, 0x4a, 0xa6, 0xb1, 0x16, 0x39, 0x67, 0x54, 0x47, 0x78, 0x1a,
	0x51, 0xe6, 0x1b, 0xe8, 0xa8, 0xa0, 0x37, 0x03, 0x63, 0x76, 0xa0, 0xfe, 0x81, 0x32, 0x2e, 0x71,
	0x73, 0xa6, 0x87, 0xef, 0x3c, 0xdf, 0x91, 0xd6, 0x12, 0xab, 0xf9, 0x1c, 0x9a, 0xf1, 0x51, 0x31,
	0xd4, 0x32, 0xff, 0x53, 0x83, 0xce, 0x80, 0xbd, 0x97, 0x15, 0xb2, 0xeb, 0x64, 0x60, 0x42, 0xcb,
	0xc2, 0xc4, 0x97, 0x07, 0x7a, 0xe7, 0x80, 0xa0, 0x71, 0x11, 0x08, 0x22, 0x58, 0x5c, 0x4e, 0x61,
	0x51, 0x81, 0x95, 0x66, 0x16, 0x56, 0x62, 0xc8, 0x6a, 0xcd, 0x82, 0x2c, 0x98, 0x0d, 0x59, 0xed,
	0x0c, 0x64, 0xa9, 0xed, 0xbc, 0x3e, 0xa7, 0x9d, 0x37, 0x66, 0xb7, 0xf3, 0xed, 0x6c, 0x3b, 0x67,
	0x27, 0xe0, 0xe3, 0x2b, 0x4d, 0xc0, 0x27, 0x97, 0x9f, 0x80, 0x4f, 0x4b, 0x4e, 0xc0, 0x4f, 0xab,
	0xb0, 0x9a, 0x54, 0xc5, 0x81, 0xb0, 0x84, 0x6b, 0x17, 0x9c, 0x82, 0xb3, 0x1a, 0x38, 0x4a, 0x5e,
	0x2d, 0x93, 0xbc, 0x39, 0xa5, 0x90, 0x94, 0x4e, 0x43, 0x2d, 0x1d, 0x75, 0x42, 0x2d, 0x9f, 0x9b,
	0x50, 0xd7, 0x51, 0x08, 0x65, 0x13, 0x9e, 0x4d, 0xeb, 0xfd, 0x4b, 0xa4, 0x35, 0x93, 0x9e, 0x5e,
	0xb9, 0xf4, 0x28, 0x35, 0xf1, 0xa0, 0x4c, 0x4d, 0x98, 0x7f, 0x05, 0x3d, 0xc9, 0xea, 0x20, 0x91,
	0x76, 0x31, 0xb1, 0x6a, 0xb8, 0x2b, 0xe7, 0xc2, 0x9d, 0x31, 0xbc, 0x5d, 0xb2, 0xae, 0x3e, 0x28,
	0x65, 0xf5, 0x52, 0xd6, 0x69, 0x39, 0xed, 0xa9, 0xe7, 0xab, 0xa5, 0x3c, 0xff, 0xbb, 0x06, 0xed,
	0x44, 0x73, 0x3f, 0x54, 0x3a, 0x5f, 0xcb, 0x74, 0x7e, 0x82, 0x67, 0x15, 0x15, 0xcf, 0x36, 0xa0,
	0x31, 0x09, 0xc6, 0xc3, 0x08, 0xe6, 0xea, 0x83, 0x88, 0xc2, 0xd2, 0x98, 0x5a, 0xc7, 0x72, 0x30,
	0xd5, 0x07, 0xf4, 0x3d, 0xbf, 0xb4, 0xcd, 0x1f, 0x2a, 0xce, 0xf7, 0x43, 0xac, 0x0c, 0x74, 0xfe,
	0x94, 0x85, 0xb1, 0xf3, 0xa7, 0x2c, 0x44, 0x03, 0xce, 0xac, 0x51, 0x10, 0x37, 0x95, 0x24, 0xcc,
	0xbf, 0xe0, 0xd5, 0xe9, 0x28, 0x54, 0x56, 0xf2, 0x1d, 0xa8, 0xb9, 0x93, 0x23, 0x2f, 0xda, 0xc8,
	0xef, 0xcd, 0xdf, 0x07, 0xe4, 0x04, 0x44, 0x5e, 0xfd, 0xfb, 0x89, 0xd7, 0x95, 0xf9, 0x7b, 0x3c,
	0x29, 0x3a, 0x20, 0xb6, 0x38, 0x2c, 0xe6, 0xdf, 0x34, 0x58, 0x53, 0x0c, 0x90, 0x13, 0xfd, 0x45,
	0xc6, 0x82, 0xdc, 0x37, 0xc1, 0x15, 0x4d, 0xf8, 0xbf, 0x96, 0x89, 0xc1, 0xaf, 0x5d, 0x2e, 0x14,
	0x61, 0x5a, 0x29, 0x61, 0xb4, 0xf3, 0x79, 0xc2, 0x1a, 0x91, 0x11, 0xdd, 0x81, 0x24, 0x92, 0x74,
	0x56, 0xe9, 0x50, 0xa6, 0x13, 0x37, 0x9d, 0x91, 0x75, 0x9c, 0x6c, 0x3a, 0x23, 0xeb, 0x18, 0x43,
	0x3f, 0x72, 0xb9, 0x88, 0xaa, 0x3f, 0x37, 0xf4, 0xc8, 0x8b, 0xe6, 0xdf, 0x50, 0xcc, 0xdf, 0xc7,
	0x25, 0xd6, 0xbe, 0xbc, 0x03, 0x3f, 0x80, 0x65, 0x1e, 0x72, 0xc1, 0xc6, 0xbc, 0xa0, 0x15, 0x31,
	0xbb, 0xfe, 0x1d, 0xa8, 0xe3, 0x6a, 0xc7, 0x8d, 0x4e, 0xa1, 0x7b, 0x92, 0xd9, 0xb4, 0xd1, 0xfa,
	0xa8, 0x76, 0x63, 0x4c, 0x9b, 0xd1, 0xba, 0x3f, 0x81, 0x66, 0x84, 0x71, 0x61, 0x94, 0xdf, 0x7c,
	0x54, 0x4c, 0x6e, 0x98, 0xff, 0xd4, 0xe0, 0xe6, 0x79, 0x2d, 0x88, 0x95, 0xe5, 0x20, 0x22, 0x8b,
	0xcd, 0xed, 0xf2, 0xd8, 0x6c, 0xfe, 0x4f, 0x53, 0xa7, 0x1f, 0xb3, 0x7c, 0xfb, 0x44, 0x81, 0x00,
	0xed, 0x3c, 0x04, 0x14, 0x5c, 0x8a, 0x14, 0x60, 0x68, 0xcb, 0x25, 0x21, 0x9e, 0x79, 0x77, 0xa0,
	0x65, 0x09, 0xe1, 0xbb, 0xc3, 0x40, 0x30, 0x4a, 0x4b, 0x6b, 0x90, 0x1e, 0x24, 0xf3, 0xa7, 0x9b,
	0xce, 0x1f, 0xf3, 0x1f, 0x1a, 0xac, 0x24, 0x16, 0xbe, 0xb2, 0x84, 0x7d, 0x82, 0x21, 0x39, 0x65,
	0xa1, 0xdc, 0x18, 0x65, 0xa4, 0x12, 0x5a, 0x31, 0xbe, 0x32, 0x13, 0xbf, 0xaa, 0x0a, 0x7e, 0xc5,
	0x0e, 0xd5, 0x66, 0x39, 0x54, 0x57, 0x1c, 0x32, 0x3f, 0xd2, 0x60, 0x5d, 0x2d, 0xe9, 0x45, 0x09,
	0x53, 0x1e, 0xac, 0x15, 0x7a, 0x38, 0x25, 0x0f, 0xd6, 0xb4, 0x05, 0xaa, 0xe5, 0x5a, 0xe0, 0xea,
	0x79, 0xfe, 0x4c, 0x83, 0x6e, 0x8a, 0xc8, 0x16, 0x67, 0x5f, 0xe7, 0x1d, 0xc7, 0xf4, 0xce, 0xad,
	0x74, 0x41, 0xd9, 0xc6, 0xda, 0xc8, 0x64, 0x2a, 0x9d, 0x99, 0xe9, 0x23, 0xb1, 0xa6, 0x3e, 0x12,
	0xcd, 0x7f, 0x67, 0x21, 0x6f, 0xae, 0x4e, 0x7c, 0x96, 0x0b, 0x7c, 0xca, 0x45, 0x60, 0x4c, 0xc4,
	0xe5, 0xeb, 0x42, 0x29, 0xb5, 0x5a, 0xa6, 0xd4, 0xcc, 0x7f, 0x65, 0x0d, 0xfa, 0x1d, 0x1d, 0x7f,
	0x35, 0xc5, 0xaa, 0x2b, 0x23, 0xa3, 0x25, 0x47, 0xc2, 0xce, 0xc7, 0x37, 0xa1, 0x1b, 0x63, 0x8c,
	0x7f, 0xe6, 0xda, 0x4c, 0xff, 0x2d, 0x34, 0x76, 0x1d, 0xe7, 0xf5, 0x84, 0xe9, 0xbd, 0xd9, 0x82,
	0xd3, 0x77, 0xda, 0xe6, 0xc3, 0xb9, 0xaa, 0x53, 0xf4, 0x36, 0x97, 0xf4, 0x7d, 0x68, 0xec, 0x31,
	0x81, 0x22, 0xe7, 0xd8, 0xfa, 0x3e, 0x60, 0x5c, 0x20, 0x73, 0x51, 0x89, 0x07, 0xd0, 0xdc, 0x63,
	0xd1, 0xa3, 0x3e, 0x57, 0xe6, 0x37, 0x72, 0x64, 0x92, 0x18, 0x12, 0xda, 0x42, 0xa1, 0xe1, 0x6f,
	0xb0, 0xbf, 0xae, 0xcb, 0xd2, 0x57, 0xd0, 0x1a, 0xb0, 0xb1, 0x77, 0xc6, 0x0a, 0xb9, 0x7f, 0x77,
	0xae, 0xd0, 0x48, 0xdc, 0x3b, 0xe8, 0xee, 0x31, 0xb1, 0x3b, 0x1a, 0xf5, 0xc3, 0xd7, 0x84, 0xe8,
	0xf7, 0x17, 0x26, 0xa9, 0x1f, 0xe6, 0xda, 0x89, 0x4b, 0x8c, 0xb9, 0xa4, 0xbf, 0x85, 0xce, 0x1e,
	0x13, 0x48, 0xf4, 0xc3, 0xbe, 0xf7, 0xe7, 0x85, 0xa6, 0xee, 0x5b, 0xc7, 0xac, 0xa8, 0xdc, 0x38,
	0xa8, 0xb4, 0x2b, 0x2d, 0x12, 0x8a, 0x0c, 0x45, 0x85, 0xbe, 0x83, 0x36, 0x09, 0xfd, 0xa5, 0x3b,
	0x12, 0xcc, 0xd7, 0x1f, 0x2c, 0x10, 0x2b, 0x59, 0x8a, 0x0b, 0xee, 0x26, 0x51, 0xc8, 0x2d, 0x83,
	0x32, 0x16, 0x1f, 0xc2, 0xca, 0x1e, 0x13, 0xfb, 0xf2, 0xcf, 0x86, 0xc5, 0x62, 0xf1, 0x28, 0x47,
	0xb2, 0x5c, 0xdf, 0xc8, 0x68, 0x4c, 0x1d, 0xbd, 0x90, 0x39, 0x3e, 0x92, 0x0b, 0x84, 0xc3, 0x5c,
	0x88, 0x19, 0x24, 0x86, 0xfa, 0x16, 0x24, 0x3e, 0xd1, 0x5c, 0x7a, 0xb0, 0xb8, 0xd2, 0x2c, 0xce,
	0xf2, 0xcb, 0xf7, 0x8f, 0xd0, 0x91, 0x12, 0x23, 0x20, 0x7e, 0xb8, 0x50, 0xa6, 0x64, 0xca, 0x0d,
	0x84, 0x64, 0x33, 0x97, 0xf4, 0xd7, 0xd0, 0x96, 0xd2, 0x7f, 0x4e, 0xc3, 0xec, 0xea, 0xdd, 0xf6,
	0x36, 0x0e, 0xc0, 0x1b, 0x7c, 0x70, 0x5f, 0x39, 0x63, 0x52, 0x96, 0xac, 0x86, 0x28, 0x0c, 0xf1,
	0x03, 0xff, 0xfa, 0x64, 0x3b, 0xb0, 0xb2, 0x3b, 0x9d, 0xb2, 0x89, 0x93, 0xac, 0xc8, 0x8f, 0x16,
	0x06, 0x39, 0x66, 0xdb, 0x7c, 0x9c, 0x57, 0x6f, 0xe9, 0xd2, 0xb2, 0xa4, 0xff, 0x09, 0xd6, 0x0e,
	0x82, 0xa1, 0xf0, 0x2d, 0x5b, 0x24, 0x7a, 0x72, 0xe3, 0x5d, 0x4a, 0xc3, 0x09, 0xac, 0x49, 0x9f,
	0x94, 0x9d, 0xee, 0x5b, 0x45, 0x3c, 0x71, 0x19, 0x2f, 0xa7, 0xe9, 0x10, 0x3a, 0x72, 0xc1, 0x8e,
	0x1e, 0x44, 0x39, 0x45, 0x49, 0xac, 0x45, 0xfb, 0xfe, 0xf7, 0xd0, 0x96, 0x17, 0xe4, 0x82, 0x6c,
	0x2e, 0x14, 0x4d, 0x3c, 0x45, 0x25, 0xff, 0x81, 0xa0, 0xaa, 0x9f, 0xbe, 0x84, 0x1e, 0xe6, 0x4c,
	0x02, 0x64, 0x2c, 0x8b, 0xda, 0xaf, 0x70, 0x95, 0xbb, 0xae, 0x51, 0xf8, 0x46, 0x6d, 0xfe, 0xfc,
	0x38, 0x13, 0x53, 0x7e, 0x8f, 0x1e, 0xc2, 0xaa, 0x94, 0x9a, 0xfe, 0x31, 0xe9, 0x9b, 0x0b, 0x05,
	0x27, 0x7c, 0xf9, 0xb2, 0x13, 0x8b, 0xa3, 0xbf, 0x13, 0x2d, 0xb6, 0x58, 0x32, 0x15, 0x41, 0x95,
	0xa8, 0xfb, 0x93, 0x01, 0x36, 0x4f, 0xae, 0x64, 0x8b, 0x30, 0x3b, 0x4f, 0x6e, 0x5f, 0x3f, 0x5c,
	0x3b, 0xff, 0x0f, 0xd5, 0x61, 0x83, 0x4e, 0x5e, 0x7c, 0x11, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xa1,
	0x2d, 0x84, 0x9e, 0x1d, 0x00, 0x00,
}
