// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/vocabulary/graph.proto

package vocabulary

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GraphService service

func NewGraphServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GraphService service

type GraphService interface {
}

type graphService struct {
	c    client.Client
	name string
}

func NewGraphService(name string, c client.Client) GraphService {
	return &graphService{
		c:    c,
		name: name,
	}
}

// Server API for GraphService service

type GraphServiceHandler interface {
}

func RegisterGraphServiceHandler(s server.Server, hdlr GraphServiceHandler, opts ...server.HandlerOption) error {
	type graphService interface {
	}
	type GraphService struct {
		graphService
	}
	h := &graphServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&GraphService{h}, opts...))
}

type graphServiceHandler struct {
	GraphServiceHandler
}
