// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/vocabulary/graph.proto

package vocabulary

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cover                string   `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Entity               string   `protobuf:"bytes,4,opt,name=entity,proto3" json:"entity,omitempty"`
	Labels               []string `protobuf:"bytes,21,rep,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f4112fd2703b34, []int{0}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeInfo) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *NodeInfo) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func (m *NodeInfo) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type LinkInfo struct {
	Id                   int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Relation             string        `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	Direction            DirectionType `protobuf:"varint,4,opt,name=direction,proto3,enum=omo.msp.vocabulary.DirectionType" json:"direction,omitempty"`
	From                 string        `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To                   string        `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LinkInfo) Reset()         { *m = LinkInfo{} }
func (m *LinkInfo) String() string { return proto.CompactTextString(m) }
func (*LinkInfo) ProtoMessage()    {}
func (*LinkInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f4112fd2703b34, []int{1}
}

func (m *LinkInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkInfo.Unmarshal(m, b)
}
func (m *LinkInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkInfo.Marshal(b, m, deterministic)
}
func (m *LinkInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkInfo.Merge(m, src)
}
func (m *LinkInfo) XXX_Size() int {
	return xxx_messageInfo_LinkInfo.Size(m)
}
func (m *LinkInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LinkInfo proto.InternalMessageInfo

func (m *LinkInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LinkInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LinkInfo) GetRelation() string {
	if m != nil {
		return m.Relation
	}
	return ""
}

func (m *LinkInfo) GetDirection() DirectionType {
	if m != nil {
		return m.Direction
	}
	return DirectionType_Double
}

func (m *LinkInfo) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *LinkInfo) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type GraphInfo struct {
	Center               string      `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	Nodes                []*NodeInfo `protobuf:"bytes,21,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Links                []*LinkInfo `protobuf:"bytes,22,rep,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GraphInfo) Reset()         { *m = GraphInfo{} }
func (m *GraphInfo) String() string { return proto.CompactTextString(m) }
func (*GraphInfo) ProtoMessage()    {}
func (*GraphInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f4112fd2703b34, []int{2}
}

func (m *GraphInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphInfo.Unmarshal(m, b)
}
func (m *GraphInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphInfo.Marshal(b, m, deterministic)
}
func (m *GraphInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphInfo.Merge(m, src)
}
func (m *GraphInfo) XXX_Size() int {
	return xxx_messageInfo_GraphInfo.Size(m)
}
func (m *GraphInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GraphInfo proto.InternalMessageInfo

func (m *GraphInfo) GetCenter() string {
	if m != nil {
		return m.Center
	}
	return ""
}

func (m *GraphInfo) GetNodes() []*NodeInfo {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *GraphInfo) GetLinks() []*LinkInfo {
	if m != nil {
		return m.Links
	}
	return nil
}

type ReqNodeAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Entity               string   `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	Label                string   `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Cover                string   `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqNodeAdd) Reset()         { *m = ReqNodeAdd{} }
func (m *ReqNodeAdd) String() string { return proto.CompactTextString(m) }
func (*ReqNodeAdd) ProtoMessage()    {}
func (*ReqNodeAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f4112fd2703b34, []int{3}
}

func (m *ReqNodeAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqNodeAdd.Unmarshal(m, b)
}
func (m *ReqNodeAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqNodeAdd.Marshal(b, m, deterministic)
}
func (m *ReqNodeAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqNodeAdd.Merge(m, src)
}
func (m *ReqNodeAdd) XXX_Size() int {
	return xxx_messageInfo_ReqNodeAdd.Size(m)
}
func (m *ReqNodeAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqNodeAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqNodeAdd proto.InternalMessageInfo

func (m *ReqNodeAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqNodeAdd) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func (m *ReqNodeAdd) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *ReqNodeAdd) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

type ReplyNodeInfo struct {
	Info                 *NodeInfo    `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyNodeInfo) Reset()         { *m = ReplyNodeInfo{} }
func (m *ReplyNodeInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyNodeInfo) ProtoMessage()    {}
func (*ReplyNodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f4112fd2703b34, []int{4}
}

func (m *ReplyNodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyNodeInfo.Unmarshal(m, b)
}
func (m *ReplyNodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyNodeInfo.Marshal(b, m, deterministic)
}
func (m *ReplyNodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyNodeInfo.Merge(m, src)
}
func (m *ReplyNodeInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyNodeInfo.Size(m)
}
func (m *ReplyNodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyNodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyNodeInfo proto.InternalMessageInfo

func (m *ReplyNodeInfo) GetInfo() *NodeInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyNodeInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReqLinkAdd struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Direction            DirectionType `protobuf:"varint,2,opt,name=direction,proto3,enum=omo.msp.vocabulary.DirectionType" json:"direction,omitempty"`
	Key                  string        `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	From                 string        `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To                   string        `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	Relation             string        `protobuf:"bytes,6,opt,name=relation,proto3" json:"relation,omitempty"`
	Weight               uint32        `protobuf:"varint,7,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReqLinkAdd) Reset()         { *m = ReqLinkAdd{} }
func (m *ReqLinkAdd) String() string { return proto.CompactTextString(m) }
func (*ReqLinkAdd) ProtoMessage()    {}
func (*ReqLinkAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f4112fd2703b34, []int{5}
}

func (m *ReqLinkAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLinkAdd.Unmarshal(m, b)
}
func (m *ReqLinkAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLinkAdd.Marshal(b, m, deterministic)
}
func (m *ReqLinkAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLinkAdd.Merge(m, src)
}
func (m *ReqLinkAdd) XXX_Size() int {
	return xxx_messageInfo_ReqLinkAdd.Size(m)
}
func (m *ReqLinkAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLinkAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLinkAdd proto.InternalMessageInfo

func (m *ReqLinkAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqLinkAdd) GetDirection() DirectionType {
	if m != nil {
		return m.Direction
	}
	return DirectionType_Double
}

func (m *ReqLinkAdd) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqLinkAdd) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ReqLinkAdd) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ReqLinkAdd) GetRelation() string {
	if m != nil {
		return m.Relation
	}
	return ""
}

func (m *ReqLinkAdd) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type ReplyLinkInfo struct {
	Info                 *LinkInfo    `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyLinkInfo) Reset()         { *m = ReplyLinkInfo{} }
func (m *ReplyLinkInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyLinkInfo) ProtoMessage()    {}
func (*ReplyLinkInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f4112fd2703b34, []int{6}
}

func (m *ReplyLinkInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyLinkInfo.Unmarshal(m, b)
}
func (m *ReplyLinkInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyLinkInfo.Marshal(b, m, deterministic)
}
func (m *ReplyLinkInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyLinkInfo.Merge(m, src)
}
func (m *ReplyLinkInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyLinkInfo.Size(m)
}
func (m *ReplyLinkInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyLinkInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyLinkInfo proto.InternalMessageInfo

func (m *ReplyLinkInfo) GetInfo() *LinkInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyLinkInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReqGraphPath struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGraphPath) Reset()         { *m = ReqGraphPath{} }
func (m *ReqGraphPath) String() string { return proto.CompactTextString(m) }
func (*ReqGraphPath) ProtoMessage()    {}
func (*ReqGraphPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f4112fd2703b34, []int{7}
}

func (m *ReqGraphPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGraphPath.Unmarshal(m, b)
}
func (m *ReqGraphPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGraphPath.Marshal(b, m, deterministic)
}
func (m *ReqGraphPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGraphPath.Merge(m, src)
}
func (m *ReqGraphPath) XXX_Size() int {
	return xxx_messageInfo_ReqGraphPath.Size(m)
}
func (m *ReqGraphPath) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGraphPath.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGraphPath proto.InternalMessageInfo

func (m *ReqGraphPath) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ReqGraphPath) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type ReplyGraphInfo struct {
	Graph                *GraphInfo   `protobuf:"bytes,1,opt,name=graph,proto3" json:"graph,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyGraphInfo) Reset()         { *m = ReplyGraphInfo{} }
func (m *ReplyGraphInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyGraphInfo) ProtoMessage()    {}
func (*ReplyGraphInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f4112fd2703b34, []int{8}
}

func (m *ReplyGraphInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyGraphInfo.Unmarshal(m, b)
}
func (m *ReplyGraphInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyGraphInfo.Marshal(b, m, deterministic)
}
func (m *ReplyGraphInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyGraphInfo.Merge(m, src)
}
func (m *ReplyGraphInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyGraphInfo.Size(m)
}
func (m *ReplyGraphInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyGraphInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyGraphInfo proto.InternalMessageInfo

func (m *ReplyGraphInfo) GetGraph() *GraphInfo {
	if m != nil {
		return m.Graph
	}
	return nil
}

func (m *ReplyGraphInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeInfo)(nil), "omo.msp.vocabulary.NodeInfo")
	proto.RegisterType((*LinkInfo)(nil), "omo.msp.vocabulary.LinkInfo")
	proto.RegisterType((*GraphInfo)(nil), "omo.msp.vocabulary.GraphInfo")
	proto.RegisterType((*ReqNodeAdd)(nil), "omo.msp.vocabulary.ReqNodeAdd")
	proto.RegisterType((*ReplyNodeInfo)(nil), "omo.msp.vocabulary.ReplyNodeInfo")
	proto.RegisterType((*ReqLinkAdd)(nil), "omo.msp.vocabulary.ReqLinkAdd")
	proto.RegisterType((*ReplyLinkInfo)(nil), "omo.msp.vocabulary.ReplyLinkInfo")
	proto.RegisterType((*ReqGraphPath)(nil), "omo.msp.vocabulary.ReqGraphPath")
	proto.RegisterType((*ReplyGraphInfo)(nil), "omo.msp.vocabulary.ReplyGraphInfo")
}

func init() {
	proto.RegisterFile("proto/vocabulary/graph.proto", fileDescriptor_32f4112fd2703b34)
}

var fileDescriptor_32f4112fd2703b34 = []byte{
	// 648 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x4e, 0xdb, 0x40,
	0x10, 0xc6, 0x4e, 0x62, 0x92, 0xe1, 0x47, 0x68, 0x45, 0x23, 0x2b, 0x82, 0x36, 0xf8, 0xc4, 0x29,
	0x54, 0xe1, 0xd0, 0x63, 0x45, 0x55, 0x81, 0x2a, 0x55, 0xb4, 0x5a, 0x2a, 0x55, 0xea, 0xcd, 0xd8,
	0x03, 0xac, 0xb0, 0xbd, 0xc1, 0x5e, 0x52, 0xa5, 0x87, 0xbe, 0x40, 0x1f, 0xa6, 0x4f, 0xd1, 0x53,
	0x5f, 0xaa, 0xda, 0xb1, 0xbd, 0x06, 0x12, 0x07, 0x0b, 0x7a, 0xf3, 0x8c, 0x67, 0xbe, 0xf9, 0xe6,
	0x9b, 0xcf, 0x09, 0xec, 0x4c, 0x52, 0xa9, 0xe4, 0xc1, 0x54, 0x06, 0xfe, 0xf9, 0x6d, 0xe4, 0xa7,
	0xb3, 0x83, 0xcb, 0xd4, 0x9f, 0x5c, 0x8d, 0x28, 0xcd, 0x98, 0x8c, 0xe5, 0x28, 0xce, 0x26, 0xa3,
	0xea, 0xfd, 0x60, 0x77, 0xae, 0x23, 0x90, 0x71, 0x2c, 0x93, 0xbc, 0xc5, 0x53, 0xd0, 0x3d, 0x95,
	0x21, 0x7e, 0x48, 0x2e, 0x24, 0xdb, 0x04, 0x5b, 0x84, 0xae, 0x35, 0xb4, 0xf6, 0x5b, 0xdc, 0x16,
	0x21, 0x63, 0xd0, 0x4e, 0xfc, 0x18, 0x5d, 0x7b, 0x68, 0xed, 0xf7, 0x38, 0x3d, 0xb3, 0x6d, 0xe8,
	0x04, 0x72, 0x8a, 0xa9, 0xdb, 0xa2, 0x64, 0x1e, 0xb0, 0x3e, 0x38, 0x98, 0x28, 0xa1, 0x66, 0x6e,
	0x9b, 0xd2, 0x45, 0xa4, 0xf3, 0x91, 0x7f, 0x8e, 0x51, 0xe6, 0xbe, 0x18, 0xb6, 0x74, 0x3e, 0x8f,
	0xbc, 0xdf, 0x16, 0x74, 0x3f, 0x8a, 0xe4, 0xba, 0xf1, 0xd8, 0x01, 0x74, 0x53, 0x8c, 0x7c, 0x25,
	0x64, 0x52, 0x4c, 0x36, 0x31, 0x7b, 0x0b, 0xbd, 0x50, 0xa4, 0x18, 0xd0, 0x4b, 0x3d, 0x7f, 0x73,
	0xbc, 0x37, 0x9a, 0x57, 0x62, 0xf4, 0xbe, 0x2c, 0xfa, 0x32, 0x9b, 0x20, 0xaf, 0x7a, 0xf4, 0xc0,
	0x8b, 0x54, 0xc6, 0x6e, 0x27, 0x1f, 0xa8, 0x9f, 0x35, 0x29, 0x25, 0x5d, 0x87, 0x32, 0xb6, 0x92,
	0xde, 0x2f, 0x0b, 0x7a, 0x27, 0x5a, 0x6a, 0xa2, 0xdc, 0x07, 0x27, 0xc0, 0x44, 0x61, 0x4a, 0xb4,
	0x7b, 0xbc, 0x88, 0xd8, 0x18, 0x3a, 0x89, 0x0c, 0x31, 0x5f, 0x77, 0x6d, 0xbc, 0xb3, 0x88, 0x46,
	0x29, 0x37, 0xcf, 0x4b, 0x75, 0x4f, 0x24, 0x92, 0xeb, 0xcc, 0xed, 0xd7, 0xf7, 0x94, 0x5a, 0xf1,
	0xbc, 0xd4, 0x0b, 0x01, 0x38, 0xde, 0x68, 0xa4, 0xa3, 0xb0, 0x12, 0xcc, 0xba, 0x23, 0x58, 0x75,
	0x11, 0xfb, 0xde, 0x45, 0xb6, 0xa1, 0x43, 0x37, 0x28, 0xef, 0x47, 0x41, 0x75, 0xd5, 0xf6, 0x9d,
	0xab, 0x7a, 0x3f, 0x60, 0x83, 0xe3, 0x24, 0x9a, 0x19, 0x83, 0xbc, 0x86, 0xb6, 0x48, 0x2e, 0x24,
	0x0d, 0x7a, 0x6c, 0x3b, 0xaa, 0x64, 0x6f, 0xc0, 0xc9, 0x94, 0xaf, 0x6e, 0x33, 0xa2, 0xb1, 0x36,
	0x7e, 0xb5, 0xa8, 0x87, 0x86, 0x9c, 0x51, 0x19, 0x2f, 0xca, 0xbd, 0xbf, 0x16, 0xad, 0xa8, 0x17,
	0xaf, 0x5b, 0xf1, 0xde, 0xdd, 0xed, 0x27, 0xdc, 0x7d, 0x0b, 0x5a, 0xd7, 0x38, 0x2b, 0x94, 0xd0,
	0x8f, 0xc6, 0x09, 0xed, 0x39, 0x27, 0x74, 0x4a, 0x27, 0xdc, 0xb3, 0xa2, 0xf3, 0xc0, 0x8a, 0x7d,
	0x70, 0xbe, 0xa3, 0xb8, 0xbc, 0x52, 0xee, 0xea, 0xd0, 0xda, 0xdf, 0xe0, 0x45, 0x64, 0x94, 0x34,
	0x9e, 0x6f, 0xa0, 0xa4, 0xb9, 0xf9, 0x33, 0x95, 0x1c, 0xc3, 0x3a, 0xc7, 0x1b, 0xf2, 0xee, 0x67,
	0x5f, 0x5d, 0x99, 0x1d, 0xad, 0xb9, 0x1d, 0x6d, 0xe3, 0xf6, 0x9f, 0xb0, 0x49, 0x50, 0x95, 0xe3,
	0x0f, 0xa1, 0x43, 0xbf, 0x34, 0x05, 0xe3, 0xdd, 0x45, 0xd3, 0x4d, 0x35, 0xcf, 0x6b, 0x9f, 0xcc,
	0x79, 0xfc, 0xc7, 0x81, 0x75, 0x42, 0x3b, 0xc3, 0x74, 0x2a, 0x02, 0x64, 0xa7, 0xb0, 0x7a, 0x14,
	0x86, 0xda, 0x5c, 0xec, 0xe5, 0x62, 0x90, 0xf2, 0x6b, 0x18, 0xec, 0xd5, 0x0e, 0x29, 0xbd, 0xe9,
	0xad, 0x14, 0x78, 0x5a, 0xe2, 0x5a, 0xbc, 0xc2, 0x7a, 0x4b, 0xf0, 0xca, 0x0b, 0x11, 0x1e, 0x70,
	0x8c, 0xe5, 0x14, 0x89, 0x62, 0xcd, 0x9e, 0x37, 0xb7, 0x98, 0x29, 0xdd, 0x30, 0xd8, 0xad, 0xc5,
	0x7c, 0x88, 0x47, 0x14, 0x9f, 0x8f, 0xf7, 0x09, 0x56, 0x4f, 0x50, 0x35, 0x23, 0xd7, 0x48, 0xc0,
	0x1c, 0xb0, 0x19, 0xbb, 0x46, 0x0a, 0x72, 0xe8, 0x1d, 0x8b, 0x84, 0x4e, 0x9c, 0x3d, 0x0e, 0xe9,
	0xd5, 0x42, 0x1a, 0x13, 0x12, 0x66, 0x57, 0x63, 0x92, 0xed, 0x87, 0x35, 0x90, 0xe6, 0xc3, 0x68,
	0x8c, 0x49, 0x3c, 0x29, 0xf5, 0xbf, 0x78, 0x7e, 0x85, 0xf5, 0x13, 0x54, 0xfa, 0x1b, 0x10, 0x99,
	0x12, 0x01, 0xdb, 0x5b, 0x02, 0x7b, 0x2c, 0x22, 0x85, 0xe9, 0x12, 0x60, 0x03, 0xe3, 0xad, 0xbc,
	0x63, 0xdf, 0xb6, 0x1e, 0xfe, 0xfd, 0x9f, 0x3b, 0x94, 0x39, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff,
	0x82, 0x95, 0x61, 0x92, 0x4b, 0x08, 0x00, 0x00,
}
