// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/vocabulary/template.proto

package vocabulary

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TemplateType int32

const (
	TemplateType_Student TemplateType = 0
	TemplateType_Teacher TemplateType = 1
)

var TemplateType_name = map[int32]string{
	0: "Student",
	1: "Teacher",
}

var TemplateType_value = map[string]int32{
	"Student": 0,
	"Teacher": 1,
}

func (x TemplateType) String() string {
	return proto.EnumName(TemplateType_name, int32(x))
}

func (TemplateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5b79888774522469, []int{0}
}

type TemplateInfo struct {
	Uid                  string           `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 TemplateType     `protobuf:"varint,3,opt,name=type,proto3,enum=omo.msp.vocabulary.TemplateType" json:"type,omitempty"`
	SkipRows             int32            `protobuf:"varint,4,opt,name=skipRows,proto3" json:"skipRows,omitempty"`
	Columns              map[string]int32 `protobuf:"bytes,5,rep,name=columns,proto3" json:"columns,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Url                  string           `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Comments             string           `protobuf:"bytes,7,opt,name=comments,proto3" json:"comments,omitempty"`
	Creator              string           `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string           `protobuf:"bytes,9,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TemplateInfo) Reset()         { *m = TemplateInfo{} }
func (m *TemplateInfo) String() string { return proto.CompactTextString(m) }
func (*TemplateInfo) ProtoMessage()    {}
func (*TemplateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b79888774522469, []int{0}
}

func (m *TemplateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateInfo.Unmarshal(m, b)
}
func (m *TemplateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateInfo.Marshal(b, m, deterministic)
}
func (m *TemplateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateInfo.Merge(m, src)
}
func (m *TemplateInfo) XXX_Size() int {
	return xxx_messageInfo_TemplateInfo.Size(m)
}
func (m *TemplateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateInfo proto.InternalMessageInfo

func (m *TemplateInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TemplateInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TemplateInfo) GetType() TemplateType {
	if m != nil {
		return m.Type
	}
	return TemplateType_Student
}

func (m *TemplateInfo) GetSkipRows() int32 {
	if m != nil {
		return m.SkipRows
	}
	return 0
}

func (m *TemplateInfo) GetColumns() map[string]int32 {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *TemplateInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *TemplateInfo) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func (m *TemplateInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *TemplateInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReqTemplateAdd struct {
	Operator             string           `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 TemplateType     `protobuf:"varint,3,opt,name=type,proto3,enum=omo.msp.vocabulary.TemplateType" json:"type,omitempty"`
	SkipRows             int32            `protobuf:"varint,4,opt,name=skipRows,proto3" json:"skipRows,omitempty"`
	Columns              map[string]int32 `protobuf:"bytes,5,rep,name=columns,proto3" json:"columns,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Url                  string           `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Comments             string           `protobuf:"bytes,7,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReqTemplateAdd) Reset()         { *m = ReqTemplateAdd{} }
func (m *ReqTemplateAdd) String() string { return proto.CompactTextString(m) }
func (*ReqTemplateAdd) ProtoMessage()    {}
func (*ReqTemplateAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b79888774522469, []int{1}
}

func (m *ReqTemplateAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTemplateAdd.Unmarshal(m, b)
}
func (m *ReqTemplateAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTemplateAdd.Marshal(b, m, deterministic)
}
func (m *ReqTemplateAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTemplateAdd.Merge(m, src)
}
func (m *ReqTemplateAdd) XXX_Size() int {
	return xxx_messageInfo_ReqTemplateAdd.Size(m)
}
func (m *ReqTemplateAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTemplateAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTemplateAdd proto.InternalMessageInfo

func (m *ReqTemplateAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqTemplateAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqTemplateAdd) GetType() TemplateType {
	if m != nil {
		return m.Type
	}
	return TemplateType_Student
}

func (m *ReqTemplateAdd) GetSkipRows() int32 {
	if m != nil {
		return m.SkipRows
	}
	return 0
}

func (m *ReqTemplateAdd) GetColumns() map[string]int32 {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *ReqTemplateAdd) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ReqTemplateAdd) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

type ReqTemplateUpdate struct {
	Operator             string           `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Uid                  string           `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string           `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                 TemplateType     `protobuf:"varint,4,opt,name=type,proto3,enum=omo.msp.vocabulary.TemplateType" json:"type,omitempty"`
	SkipRows             int32            `protobuf:"varint,5,opt,name=skipRows,proto3" json:"skipRows,omitempty"`
	Columns              map[string]int32 `protobuf:"bytes,6,rep,name=columns,proto3" json:"columns,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Url                  string           `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	Comments             string           `protobuf:"bytes,8,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReqTemplateUpdate) Reset()         { *m = ReqTemplateUpdate{} }
func (m *ReqTemplateUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqTemplateUpdate) ProtoMessage()    {}
func (*ReqTemplateUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b79888774522469, []int{2}
}

func (m *ReqTemplateUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTemplateUpdate.Unmarshal(m, b)
}
func (m *ReqTemplateUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTemplateUpdate.Marshal(b, m, deterministic)
}
func (m *ReqTemplateUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTemplateUpdate.Merge(m, src)
}
func (m *ReqTemplateUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqTemplateUpdate.Size(m)
}
func (m *ReqTemplateUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTemplateUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTemplateUpdate proto.InternalMessageInfo

func (m *ReqTemplateUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqTemplateUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqTemplateUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqTemplateUpdate) GetType() TemplateType {
	if m != nil {
		return m.Type
	}
	return TemplateType_Student
}

func (m *ReqTemplateUpdate) GetSkipRows() int32 {
	if m != nil {
		return m.SkipRows
	}
	return 0
}

func (m *ReqTemplateUpdate) GetColumns() map[string]int32 {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *ReqTemplateUpdate) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ReqTemplateUpdate) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

type ReplyTemplateInfo struct {
	Info                 *TemplateInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReplyTemplateInfo) Reset()         { *m = ReplyTemplateInfo{} }
func (m *ReplyTemplateInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyTemplateInfo) ProtoMessage()    {}
func (*ReplyTemplateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b79888774522469, []int{3}
}

func (m *ReplyTemplateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyTemplateInfo.Unmarshal(m, b)
}
func (m *ReplyTemplateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyTemplateInfo.Marshal(b, m, deterministic)
}
func (m *ReplyTemplateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyTemplateInfo.Merge(m, src)
}
func (m *ReplyTemplateInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyTemplateInfo.Size(m)
}
func (m *ReplyTemplateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyTemplateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyTemplateInfo proto.InternalMessageInfo

func (m *ReplyTemplateInfo) GetInfo() *TemplateInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyTemplateInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyTemplateList struct {
	Flag                 string          `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	List                 []*TemplateInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Status               *ReplyStatus    `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint32          `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Pages                uint32          `protobuf:"varint,5,opt,name=pages,proto3" json:"pages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReplyTemplateList) Reset()         { *m = ReplyTemplateList{} }
func (m *ReplyTemplateList) String() string { return proto.CompactTextString(m) }
func (*ReplyTemplateList) ProtoMessage()    {}
func (*ReplyTemplateList) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b79888774522469, []int{4}
}

func (m *ReplyTemplateList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyTemplateList.Unmarshal(m, b)
}
func (m *ReplyTemplateList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyTemplateList.Marshal(b, m, deterministic)
}
func (m *ReplyTemplateList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyTemplateList.Merge(m, src)
}
func (m *ReplyTemplateList) XXX_Size() int {
	return xxx_messageInfo_ReplyTemplateList.Size(m)
}
func (m *ReplyTemplateList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyTemplateList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyTemplateList proto.InternalMessageInfo

func (m *ReplyTemplateList) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

func (m *ReplyTemplateList) GetList() []*TemplateInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ReplyTemplateList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyTemplateList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyTemplateList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func init() {
	proto.RegisterEnum("omo.msp.vocabulary.TemplateType", TemplateType_name, TemplateType_value)
	proto.RegisterType((*TemplateInfo)(nil), "omo.msp.vocabulary.TemplateInfo")
	proto.RegisterMapType((map[string]int32)(nil), "omo.msp.vocabulary.TemplateInfo.ColumnsEntry")
	proto.RegisterType((*ReqTemplateAdd)(nil), "omo.msp.vocabulary.ReqTemplateAdd")
	proto.RegisterMapType((map[string]int32)(nil), "omo.msp.vocabulary.ReqTemplateAdd.ColumnsEntry")
	proto.RegisterType((*ReqTemplateUpdate)(nil), "omo.msp.vocabulary.ReqTemplateUpdate")
	proto.RegisterMapType((map[string]int32)(nil), "omo.msp.vocabulary.ReqTemplateUpdate.ColumnsEntry")
	proto.RegisterType((*ReplyTemplateInfo)(nil), "omo.msp.vocabulary.ReplyTemplateInfo")
	proto.RegisterType((*ReplyTemplateList)(nil), "omo.msp.vocabulary.ReplyTemplateList")
}

func init() {
	proto.RegisterFile("proto/vocabulary/template.proto", fileDescriptor_5b79888774522469)
}

var fileDescriptor_5b79888774522469 = []byte{
	// 607 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x95, 0xdf, 0x6a, 0xdb, 0x30,
	0x14, 0xc6, 0x6b, 0x3b, 0x71, 0x1a, 0xa5, 0xed, 0x32, 0xb1, 0x0b, 0x13, 0x28, 0x0d, 0x86, 0x42,
	0x18, 0xcc, 0x85, 0xac, 0xb0, 0xd1, 0xbb, 0x6c, 0x8c, 0x52, 0xe8, 0x18, 0x28, 0xe9, 0xcd, 0x76,
	0xa5, 0xda, 0x27, 0x9d, 0x89, 0x6c, 0xa9, 0xb6, 0x9c, 0xe1, 0xdb, 0x3d, 0xd7, 0xae, 0x76, 0xb3,
	0xc7, 0xd8, 0x23, 0xec, 0x15, 0x86, 0xe4, 0xb8, 0xf9, 0x9f, 0x66, 0x5b, 0xd8, 0x9d, 0x8e, 0x74,
	0x74, 0xce, 0xf7, 0xfd, 0x72, 0xe4, 0xa0, 0x13, 0x91, 0x70, 0xc9, 0xcf, 0xc6, 0xdc, 0xa7, 0xb7,
	0x19, 0xa3, 0x49, 0x7e, 0x26, 0x21, 0x12, 0x8c, 0x4a, 0xf0, 0xf4, 0x09, 0xc6, 0x3c, 0xe2, 0x5e,
	0x94, 0x0a, 0x6f, 0x9a, 0xd2, 0x3a, 0x5e, 0xba, 0xe4, 0xf3, 0x28, 0xe2, 0x71, 0x71, 0xc5, 0xfd,
	0x65, 0xa2, 0x83, 0xc1, 0xa4, 0xca, 0x55, 0x3c, 0xe4, 0xb8, 0x89, 0xac, 0x2c, 0x0c, 0x1c, 0xa3,
	0x6d, 0x74, 0xea, 0x44, 0x2d, 0x31, 0x46, 0x95, 0x98, 0x46, 0xe0, 0x98, 0x7a, 0x4b, 0xaf, 0xf1,
	0x39, 0xaa, 0xc8, 0x5c, 0x80, 0x63, 0xb5, 0x8d, 0xce, 0x51, 0xb7, 0xed, 0x2d, 0x37, 0xf6, 0xca,
	0xaa, 0x83, 0x5c, 0x00, 0xd1, 0xd9, 0xb8, 0x85, 0xf6, 0xd3, 0x51, 0x28, 0x08, 0xff, 0x92, 0x3a,
	0x95, 0xb6, 0xd1, 0xa9, 0x92, 0x87, 0x18, 0x5f, 0xa2, 0x9a, 0xcf, 0x59, 0x16, 0xc5, 0xa9, 0x53,
	0x6d, 0x5b, 0x9d, 0x46, 0xf7, 0xc5, 0xa6, 0xa2, 0x4a, 0xaa, 0xf7, 0xb6, 0xc8, 0x7f, 0x17, 0xcb,
	0x24, 0x27, 0xe5, 0x6d, 0x6d, 0x20, 0x61, 0x8e, 0x3d, 0x31, 0x90, 0x30, 0xd5, 0x56, 0x79, 0x86,
	0x58, 0xa6, 0x4e, 0x4d, 0x6f, 0x3f, 0xc4, 0xd8, 0x41, 0x35, 0x3f, 0x01, 0x2a, 0x79, 0xe2, 0xec,
	0xeb, 0xa3, 0x32, 0x54, 0xb7, 0xb8, 0x80, 0x44, 0x1f, 0xd5, 0x8b, 0x5b, 0x65, 0xdc, 0xba, 0x40,
	0x07, 0xb3, 0xcd, 0x55, 0xcf, 0x11, 0xe4, 0x25, 0xb4, 0x11, 0xe4, 0xf8, 0x19, 0xaa, 0x8e, 0x29,
	0xcb, 0x0a, 0x6a, 0x55, 0x52, 0x04, 0x17, 0xe6, 0x6b, 0xc3, 0xfd, 0x61, 0xa2, 0x23, 0x02, 0xf7,
	0xa5, 0x93, 0x5e, 0x10, 0xcc, 0xb5, 0x32, 0xe6, 0x5b, 0xfd, 0x27, 0xfa, 0x57, 0x8b, 0xf4, 0xcf,
	0x56, 0x15, 0x9d, 0x97, 0xbd, 0x0b, 0xfe, 0xff, 0x44, 0xf2, 0xa7, 0x89, 0x9e, 0xce, 0x48, 0xba,
	0x11, 0x01, 0x95, 0xb0, 0x11, 0xe6, 0x64, 0xb8, 0xcd, 0xe5, 0xe1, 0xb6, 0x56, 0xe0, 0xad, 0xfc,
	0x35, 0xde, 0xea, 0x02, 0xde, 0xeb, 0x29, 0x5e, 0x5b, 0xe3, 0xed, 0x3e, 0x82, 0xb7, 0xf0, 0xb2,
	0x99, 0x70, 0x6d, 0x35, 0xe1, 0xfd, 0x1d, 0x12, 0xfe, 0x6a, 0x28, 0xc2, 0x82, 0xe5, 0x73, 0x9f,
	0x88, 0x73, 0x54, 0x09, 0xe3, 0x21, 0xd7, 0x25, 0x1a, 0x9b, 0xf9, 0xa8, 0x7c, 0xa2, 0xb3, 0xf1,
	0x2b, 0x64, 0xa7, 0x92, 0xca, 0x2c, 0xd5, 0x6d, 0x1a, 0xdd, 0x93, 0xd5, 0x08, 0x04, 0xcb, 0xfb,
	0x3a, 0x8d, 0x4c, 0xd2, 0xdd, 0xef, 0x8b, 0x22, 0xae, 0xc3, 0x54, 0xaa, 0x1f, 0x6e, 0xc8, 0xe8,
	0xdd, 0xc4, 0x87, 0x5e, 0x2b, 0x61, 0x2c, 0x4c, 0xa5, 0x63, 0x6a, 0xc6, 0x5b, 0x08, 0x53, 0xd9,
	0x33, 0xc2, 0xac, 0x3f, 0x12, 0xa6, 0xb8, 0x49, 0x2e, 0x29, 0xd3, 0x83, 0x72, 0x48, 0x8a, 0x40,
	0xed, 0x0a, 0x7a, 0x07, 0xc5, 0x10, 0x1c, 0x92, 0x22, 0x78, 0xde, 0x99, 0x7e, 0x66, 0xd5, 0xcc,
	0xe0, 0x06, 0xaa, 0xf5, 0x65, 0x16, 0x40, 0x2c, 0x9b, 0x7b, 0x2a, 0x18, 0x00, 0xf5, 0x3f, 0x43,
	0xd2, 0x34, 0xba, 0xdf, 0x2c, 0xf4, 0xa4, 0x4c, 0xed, 0x43, 0x32, 0x0e, 0x7d, 0xc0, 0x37, 0xc8,
	0xee, 0x05, 0xc1, 0x87, 0x18, 0xb0, 0xfb, 0xf8, 0xbb, 0x6c, 0x9d, 0xae, 0x35, 0x30, 0xeb, 0xde,
	0xdd, 0xc3, 0x04, 0xd9, 0x97, 0x20, 0x55, 0xd9, 0x35, 0x9e, 0xef, 0x33, 0x48, 0xa5, 0x4a, 0xde,
	0xbe, 0xe6, 0x7b, 0x54, 0x27, 0x10, 0xf1, 0x31, 0x6c, 0x55, 0xf6, 0x78, 0x6d, 0xd9, 0x39, 0x89,
	0x3d, 0xc6, 0x76, 0x21, 0x51, 0x0d, 0x8e, 0xbb, 0x87, 0x3f, 0xa1, 0x7a, 0xf1, 0xbe, 0x94, 0xc4,
	0xd3, 0xad, 0x5e, 0xe2, 0xd6, 0xfe, 0xdf, 0xe0, 0x8f, 0xcd, 0xc5, 0x7f, 0xdc, 0x5b, 0x5b, 0xef,
	0xbc, 0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x43, 0x30, 0x93, 0xc1, 0x07, 0x00, 0x00,
}
